### ISSUE TITLE
Error when testing multiple applications

### ISSUE THREAD

**Issue by catat** [calabash/calabash-android#233]
I have completed settings according to
http://blog.lesspainful.com/2013/03/15/Testing-Multiple-Android-Apps/ . 

After I perform:
calabash-android run -p android "C:\Users\user\message_1to1.feature" -v

the application starts and I get an error:
2013-04-19 17:39:22 - "C:\eclipse\android-sdk\platform-tools\adb.exe"  forward tcp: tcp:7102
2013-04-19 17:39:22 -
2013-04-19 17:39:22 - Action: get_activity_name - Params:
Exception in thread "main" java.io.FileNotFoundException:
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:214)
        at java.util.zip.ZipFile.<init>(ZipFile.java:144)
        at java.util.jar.JarFile.<init>(JarFile.java:153)
        at java.util.jar.JarFile.<init>(JarFile.java:90)
        at ManifestExtractor.main(ManifestExtractor.java:19)
2013-04-19 17:39:22 - Error communicating with test server: undefined method `attributes' for nil:NilClass
    And I go to contacts tab                       # features/step_definitions/contacts_tab_steps.rb:1
      undefined method`attributes' for nil:NilClass (NoMethodError)
      C:/Ruby193/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
      ./features/android/helpers/library.rb:18:in`block in main_screen'
      ./features/android/helpers/library.rb:17:in `loop'
      ./features/android/helpers/library.rb:17:in`main_screen'
      ./features/android/helpers/library.rb:42:in `go_to_contacts_tab'
      ./features/step_definitions/contacts_tab_steps.rb:2:in`/^I go to contacts tab$/'

Path to applications do not contain spaces and it works fine with standard hooks. Could you please fix it?

Environment:
Ruby 1.9.3-p385
Calabash-android 0.4.3.pre8
Windows 7 x64 Ultimate

**Comment by csytsma** [comment]
Can you explain what you actually changed? I don't see a difference in your two @@app1 definitions, except reducing the port number from 7103 to 7102.

What was the actual problem?
