### ISSUE TITLE
Unable to start calabash test server on emulator.

### ISSUE THREAD

**Issue by sri85** [calabash/calabash-android#444]
I am getting the following error when i try to run calabash-android run AndroidDemoProject.apk -v 

I am getting the following error , ANy help would be greatly appreciated 
C:\calabash>calabash-android run AndroidDemoProject.apk -v
2014-07-27 21:37:44 - JDK found on PATH.
2014-07-27 21:37:44 - JDK found at: C:\java
2014-07-27 21:37:44 - Android SDK found at: C:\Android
2014-07-27 21:37:44 - C:/Ruby200/bin/ruby.exe -S cucumber -v MAIN_ACTIVITY=sh.ca
laba.demoproject.AndroidDemoProjectActivity APP_PATH="C:/calabash/AndroidDemoPro
ject.apk" TEST_APP_PATH="test_servers/4251d38546a8307dd4c0aa2e9fcb2c29_0.5.1.apk
"
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansic
on/) to get coloured output on Windows
Code:
  * features/support/env.rb
DL is deprecated, please use Fiddle
  * features/support/app_installation_hooks.rb
  * features/support/app_life_cycle_hooks.rb
  * features/support/hooks.rb
  * features/step_definitions/calabash_steps.rb

Features:
  * features/my_first.feature
Parsing feature files took 0m0.019s

Feature: Demo feature

  Scenario: I can start my app                                 # features\my_fir
st.feature:2
2014-07-27 21:37:46 - First scenario in feature - reinstalling apps
2014-07-27 21:37:46 - connected_devices: ["emulator-5554"]
2014-07-27 21:37:46 - "C:\Android/platform-tools/adb.exe" -s emulator-5554 forwa
rd tcp:34778 tcp:7102
2014-07-27 21:37:46 -
2014-07-27 21:37:46 - Uninstalling: sh.calaba.demoproject.test
2014-07-27 21:37:51 - Success

2014-07-27 21:37:51 - Uninstalling: sh.calaba.demoproject
2014-07-27 21:37:53 - Success

2014-07-27 21:37:53 - Installing: test_servers/4251d38546a8307dd4c0aa2e9fcb2c29_
0.5.1.apk
1297 KB/s (544849 bytes in 0.410s)
2014-07-27 21:38:01 -   pkg: /data/local/tmp/4251d38546a8307dd4c0aa2e9fcb2c29_0.
5.1.apk

Success

2014-07-27 21:38:02 - Installing: C:/calabash/AndroidDemoProject.apk
1280 KB/s (38039 bytes in 0.029s)
2014-07-27 21:38:05 -   pkg: /data/local/tmp/AndroidDemoProject.apk

Success

2014-07-27 21:38:08 - Starting test server using:
2014-07-27 21:38:08 - "C:\Android/platform-tools/adb.exe" -s emulator-5554 shell
 am instrument -e target_package sh.calaba.demoproject -e main_activity sh.calab
a.demoproject.AndroidDemoProjectActivity -e test_server_port 7102 -e class sh.ca
laba.instrumentationbackend.InstrumentationBackend sh.calaba.demoproject.test/sh
.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
  Could not execute command to start test server (RuntimeError)
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.1/lib/calabash-androi
d/operations.rb:529:in `start_test_server_in_background'
  C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-android-0.5.1/lib/calabash-androi
d/operations.rb:110:in `start_test_server_in_background'
  C:/calabash/features/support/app_life_cycle_hooks.rb:5:in `Before'
    And I wait for "Hello World, AndroidDemoProject" to appear # calabash-androi
d-0.5.1/lib/calabash-android/steps/progress_steps.rb:22
2014-07-27 21:38:08 - java -jar C:/Ruby200/lib/ruby/gems/2.0.0/gems/calabash-and
roid-0.5.1/lib/calabash-android/lib/screenshotTaker.jar emulator-5554 "screensho
t_0.png"
2014-07-27 21:38:09 - It looks like your app is no longer running.
It could be because of a crash or because your test script shut it down.
2014-07-27 21:38:09 - Server not responding. Moving on.

Failing Scenarios:
cucumber features\my_first.feature:2 # Scenario: I can start my app

1 scenario (1 failed)
1 step (1 skipped)
0m23.292s

**Comment by TobiasRoikjer** [comment]
Calabash-Android requires the application to have INTERNET permission.
