### ISSUE TITLE
JSON parse error for getting an Android.View getBackground ()

### ISSUE THREAD

**Issue by sethrosetter** [calabash/calabash-android#460]
```
W/System.err( 5595): java.lang.RuntimeException: Could not convert result to json: {results=[android.graphics.drawable.C
olorDrawable@41ee62d0], outcome=SUCCESS}
W/System.err( 5595):    at sh.calaba.instrumentationbackend.json.JSONUtils.asJson(JSONUtils.java:15)
W/System.err( 5595):    at sh.calaba.instrumentationbackend.FranklyResult.asJson(FranklyResult.java:55)
W/System.err( 5595):    at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:181)
W/System.err( 5595):    at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:454)
W/System.err( 5595):    at java.lang.Thread.run(Thread.java:841)
W/System.err( 5595): Caused by: sh.calaba.org.codehaus.jackson.map.JsonMappingException: Conflicting getter definitions
for property "importantForAccessibility": android.view.View#isImportantForAccessibility(0 params) vs android.view.View#g
etImportantForAccessibility(0 params) (through reference chain: java.util.HashMap["results"]->java.util.ArrayList[0]->an
droid.graphics.drawable.ColorDrawable["callback"])
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.StdSerializerProvider._createAndCacheUntypedSerializer
(StdSerializerProvider.java:740)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.StdSerializerProvider.findValueSerializer(StdSerialize
rProvider.java:344)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.impl.PropertySerializerMap.findAndAddSerializer(Proper
tySerializerMap.java:39)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanPropertyWriter._findAndAddDynamic(BeanPropertyWrit
er.java:463)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter
.java:441)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.BeanSerializerBase.serializeFields(BeanSerializerB
ase.java:150)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanSerializer.serialize(BeanSerializer.java:112)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.seri
alizeContents(StdContainerSerializers.java:128)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.StdContainerSerializers$IndexedListSerializer.seri
alizeContents(StdContainerSerializers.java:77)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.AsArraySerializerBase.serialize(AsArraySerializerB
ase.java:86)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.MapSerializer.serializeFields(MapSerializer.java:2
62)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:186)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.std.MapSerializer.serialize(MapSerializer.java:23)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.StdSerializerProvider._serializeValue(StdSerializerPro
vider.java:610)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.StdSerializerProvider.serializeValue(StdSerializerProv
ider.java:256)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ObjectMapper._configAndWriteValue(ObjectMapper.java:2608)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ObjectMapper.writeValueAsString(ObjectMapper.java:2130)
W/System.err( 5595):    at sh.calaba.instrumentationbackend.json.JSONUtils.asJson(JSONUtils.java:13)
W/System.err( 5595):    ... 4 more
W/System.err( 5595): Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "importa
ntForAccessibility": android.view.View#isImportantForAccessibility(0 params) vs android.view.View#getImportantForAccessi
bility(0 params)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuild
er.java:162)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.introspect.POJOPropertyBuilder.getAccessor(POJOPropertyBui
lder.java:111)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSeriali
zerFactory.java:701)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanSerializerFactory.findBeanProperties(BeanSerialize
rFactory.java:558)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanSerializerFactory.constructBeanSerializer(BeanSeri
alizerFactory.java:430)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanSerializerFactory.findBeanSerializer(BeanSerialize
rFactory.java:343)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.BeanSerializerFactory.createSerializer(BeanSerializerF
actory.java:287)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.StdSerializerProvider._createUntypedSerializer(StdSeri
alizerProvider.java:782)
W/System.err( 5595):    at sh.calaba.org.codehaus.jackson.map.ser.StdSerializerProvider._createAndCacheUntypedSerializer
(StdSerializerProvider.java:735)
W/System.err( 5595):    ... 21 more
```

**Comment by TobiasRoikjer** [comment]
Closing issue, this was fixed a while ago :)
