### ISSUE TITLE
Can't build calabash-android gem locally

### ISSUE THREAD

**Issue by shyukri** [calabash/calabash-android#545]
Following https://github.com/calabash/calabash-android/wiki/Building-calabash-android I have problems building the gem:
```
  [antcall] Exiting /private/var/folders/z3/45tkgkc50ns76m7_dpfjhnr00000gn/T/d20150309-13443-1il5q3m/test-server/build.xml.

BUILD FAILED
/private/var/folders/z3/45tkgkc50ns76m7_dpfjhnr00000gn/T/d20150309-13443-1il5q3m/test-server/build.xml:102: The following error occurred while executing this line:
/private/var/folders/z3/45tkgkc50ns76m7_dpfjhnr00000gn/T/d20150309-13443-1il5q3m/test-server/build.xml:97: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1180)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:935)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 5 seconds
Could not build the test server. Please see the output above.
```
`ANDROID_HOME` and `JAVA_HOME` are already set

**Comment by jhansche** [comment]
There's not enough information here to show why it failed.  You'll need more context, including at least a few lines above where you started here, and the command you were using to build.
