### ISSUE TITLE
NPE at at sh.calaba.instrumentationbackend.InstrumentationBackend.tearDown(InstrumentationBackend.java:160)

### ISSUE THREAD

**Issue by fryclukasz** [calabash/calabash-android#551]
I use 0.5.2 and from time to time I get the following exception. Does anyone has any ideas why it may be happening? 

```
adjMyeD4lGJIjFlr35lbDOuKfv1NVsV3ZbQDI5C8mXsM_PjWQ1n9r4CXuNaFOP_XE3iBqDExZWjViNgdTbN-ytke5M20VpMjjPEKSxIy55mwL0vbVGwg
I/GoogleURLConnFactory( 1162): binding HttpService
I/GoogleHttpClient( 1162): Falling back to old SSLCertificateSocketFactory
I/GoogleURLConnFactory( 1162): unbinding HttpService
I/ConfigFetchService( 1162): fetch service done; releasing wakelock
I/ConfigFetchService( 1162): stopping self
I/ConfigService( 1020): onDestroy
I/System.out(28554): URI: //ping
I/System.out(28554): params: {json={}
I/System.out(28554): }
D/dalvikvm(28554): GC_FOR_ALLOC freed 2185K, 14% free 16968K/19716K, paused 93ms, total 94ms
I/System.out(28554): URI: //ready
I/System.out(28554): params: {json={}
I/System.out(28554): }
I/System.out(28554): testHook: Activity not set
I/System.out(28554): Finishing
W/System.err(28554): java.lang.NullPointerException
W/System.err(28554): 	at sh.calaba.instrumentationbackend.InstrumentationBackend.tearDown(InstrumentationBackend.java:160)
W/System.err(28554): 	at junit.framework.TestCase.runBare(TestCase.java:140)
W/System.err(28554): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
W/System.err(28554): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
W/System.err(28554): 	at junit.framework.TestResult.run(TestResult.java:118)
W/System.err(28554): 	at junit.framework.TestCase.run(TestCase.java:124)
W/System.err(28554): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
W/System.err(28554): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
W/System.err(28554): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
W/System.err(28554): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
I/ActivityManager(  526): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=testapp.app/testapp.activities.LaunchActivity} from pid 28554
D/Finsky  ( 1824): [1] 5.onFinished: Installation state replication succeeded.
```

**Comment by fryclukasz** [comment]
```
2015-03-17 10:10:59 - Starting test server using:
2015-03-17 10:10:59 - "/Users/testrunner/sdk/platform-tools/adb" -s 00143da9cde34392 shell am instrument -e target_package flipboard.app -e main_activity flipboard.activities.LaunchActivity -e test_server_port 7102 -e class sh.calaba.instrumentationbackend.InstrumentationBackend flipboard.app.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
2015-03-17 10:10:59 - Checking if instrumentation backend is ready
2015-03-17 10:10:59 - Is app running? true
2015-03-17 10:10:59 - Instrumentation backend not yet ready
2015-03-17 10:11:02 - Checking if instrumentation backend is ready
2015-03-17 10:11:02 - Is app running? true
2015-03-17 10:11:02 - Instrumentation backend not yet ready
2015-03-17 10:11:05 - Checking if instrumentation backend is ready
2015-03-17 10:11:05 - Is app running? true
2015-03-17 10:11:05 - Instrumentation backend not yet ready
2015-03-17 10:11:08 - Checking if instrumentation backend is ready
2015-03-17 10:11:08 - Is app running? true
2015-03-17 10:11:09 - Instrumentation backend not yet ready
2015-03-17 10:11:12 - Checking if instrumentation backend is ready
2015-03-17 10:11:12 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:12 - Is app running? false
2015-03-17 10:11:12 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:15 - Checking if instrumentation backend is ready
2015-03-17 10:11:15 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:15 - Is app running? false
2015-03-17 10:11:15 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:18 - Checking if instrumentation backend is ready
2015-03-17 10:11:18 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:18 - Is app running? false
2015-03-17 10:11:18 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:21 - Checking if instrumentation backend is ready
2015-03-17 10:11:21 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:21 - Is app running? false
2015-03-17 10:11:21 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:24 - Checking if instrumentation backend is ready
2015-03-17 10:11:24 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:24 - Is app running? false
2015-03-17 10:11:24 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:27 - Checking if instrumentation backend is ready
2015-03-17 10:11:27 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:27 - Is app running? false
2015-03-17 10:11:27 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:27 - java -jar /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.2/lib/calabash-android/lib/screenshotTaker.jar 00143da9cde34392 "screenshot_0.png"
2015-03-17 10:11:29 - java -jar /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.2/lib/calabash-android/lib/screenshotTaker.jar 00143da9cde34392 "screenshot_1.png"
2015-03-17 10:11:32 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-03-17 10:11:32 - Server not responding. Moving on.
```

**Comment by TobiasRoikjer** [comment]
@fryclukasz Looking at the code
```java
        try {
            solo.finalize();
        } catch (Throwable e) {
            e.printStackTrace();
        }
```
The stack trace is just printed, and should not be the cause of any issue you see. If your test-server is crashing unexpectedly, I would look elsewhere in the log.
