### ISSUE TITLE
cannot load such file -- awesome_print

### ISSUE THREAD

**Issue by gunesmes** [calabash/calabash-android#558]
I am getting this error if install awesome_print
```sh
~ sudo gem install awesome_print
Fetching: awesome_print-1.6.1.gem (100%)
Successfully installed awesome_print-1.6.1
Parsing documentation for awesome_print-1.6.1
Installing ri documentation for awesome_print-1.6.1
1 gem installed
~ calabash-android console ~/Downloads/Crashlytics.apk  ADB_DEVICE_ARG=192.168.56.101:5555
Starting calabash-android console...
Loading /Library/Ruby/Gems/2.0.0/gems/calabash-android-0.5.8/irbrc
Running irb...
Caught a LoadError: could not load 'awesome_print'
cannot load such file -- awesome_print

Use bundler (recommended) or uninstall awesome_print.

# Use bundler (recommended)
$ bundle update
$ bundle exec calabash-android console <path to apk>

# Uninstall
$ gem update --system
$ gem uninstall -Vax --force --no-abort-on-dependent awesome_print
```

if I uninstall the awesome_print, this time I am getting the following error:
```sh
~ sudo gem uninstall -Vax --force --no-abort-on-dependent awesome_print
Successfully uninstalled awesome_print-1.2.0
Successfully uninstalled awesome_print-1.6.1
~ calabash-android console ~/Downloads/Crashlytics.apk  ADB_DEVICE_ARG=192.168.56.101:5555
/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'awesome_print' (~> 1.2) among 43 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/mesutgunes/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1300:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1282:in `activate'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /usr/bin/calabash-android:22:in `<main>'
```

**Comment by TobiasRoikjer** [comment]
@gunesmes You should avoid installing gems using sudo. If you are having issues, you should use bundler as recommended.
