### ISSUE TITLE
Calabash not working with CircleCI: java.lang.RuntimeException: Could not get detect the first Activity

### ISSUE THREAD

**Issue by Gregliest** [calabash/calabash-android#575]
Hi,

I’m having trouble getting Calabash-android to work on CircleCI.  It works locally, but it appears from the exception in the sh.calaba.instrumentationbackend.InstrumentationBackend.testHook method that the instrumentation is not finding my activity.  I’ve spent a couple of days poking around, including the following:

1. I’ve verified that Calabash-android works with that circle.yml file on my local machine using version 0.5.8 on both an emulator and a device.
2. I’ve verified that the app is running/can run on CircleCI via ssh/adb and captured screenshots
3. I tried moving the calabash installation to a gem file to control versions
4. I’ve verified that ANDROID_HOME and ANT_HOME are set properly
5. I’ve tried calabash’s two emulators, API levels 21 and 22.  

I don't really understand the testHook method, so I cannot determine where or why the activity was failing to be found.  

Here’s my circle.yml:

```
machine:
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux
    ANT_HOME: ant/apache-ant-1.9.4
  java:
    version: oraclejdk7

dependencies:
  override:
    - gem install calabash-android

test:
  pre:
    - emulator -avd circleci-android22 -no-audio -no-window:
        background: true
        parallel: true
  override:
    - (echo "Running JUnit tests!")
    - (./gradlew assembleDebug)
    - circle-android wait-for-boot
    - sleep 5
    # - (./gradlew connectedAndroidTest)
    # Unlock the emulator device
    - fb-adb shell input keyevent 82
    - sleep 5
    - fb-adb shell input touchscreen swipe 370 735 371 735
    - sleep 5
    - cp app/build/outputs/apk/app-debug.apk calabash.apk
    - calabash-android resign "`pwd`/calabash.apk" -v
    - calabash-android run "`pwd`/calabash.apk" -v
    - cp calabash.apk $CIRCLE_ARTIFACTS
    - cp *.png $CIRCLE_ARTIFACTS
    - cp /tmp/junit/* $CIRCLE_TEST_REPORTS
    - adb logcat -d > $CIRCLE_ARTIFACTS/logcat.txt
```

Here’s what I think the relevant error is in the logcat.  The first is a caught exception, the second (RuntimeException) appears to be the issue.  I’ve removed my package and activity names from the log.

```
I/System.out( 1790): testHook: Activity not set
I/art     ( 1790): Background sticky concurrent mark sweep GC freed 15223(1053KB) AllocSpace objects, 5(80KB) LOS objects, 7% free, 9MB/10MB, paused 1.326ms total 198.086ms
I/System.out( 1790): Finishing
W/System.err( 1790): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jayway.android.robotium.solo.SoloEnhanced.finalize()' on a null object reference
W/System.err( 1790): 	at sh.calaba.instrumentationbackend.InstrumentationBackend.tearDown(InstrumentationBackend.java:160)
W/System.err( 1790): 	at junit.framework.TestCase.runBare(TestCase.java:140)
W/System.err( 1790): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
W/System.err( 1790): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
W/System.err( 1790): 	at junit.framework.TestResult.run(TestResult.java:118)
W/System.err( 1790): 	at junit.framework.TestCase.run(TestCase.java:124)
W/System.err( 1790): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
W/System.err( 1790): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
W/System.err( 1790): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
W/System.err( 1790): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
I/ActivityManager(  358): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=<my_package/my_activity>} from uid 10054 on display 0
I/art     ( 1790): Background partial concurrent mark sweep GC freed 2170(206KB) AllocSpace objects, 1(16KB) LOS objects, 15% free, 10MB/12MB, paused 33.532ms total 506.612ms
V/WindowManager(  358): Adding window Window{2b610964 u0 <my_package/my_activity>} at 2 of 6 (before Window{d2c641b u0 Starting <my_package>})
I/Choreographer( 1790): Skipped 32 frames!  The application may be doing too much work on its main thread.
D/gralloc_goldfish( 1790): Emulator without GPU emulation detected.
I/Choreographer( 1790): Skipped 59 frames!  The application may be doing too much work on its main thread.
I/ActivityManager(  358): Displayed <my_package/my_activity>: +12s946ms
I/TestRunner( 1790): failed: testHook(sh.calaba.instrumentationbackend.InstrumentationBackend)
I/TestRunner( 1790): ----- begin exception -----
I/TestRunner( 1790): 
I/TestRunner( 1790): java.lang.RuntimeException: Could not get detect the first Activity
I/TestRunner( 1790): 	at sh.calaba.instrumentationbackend.InstrumentationBackend.testHook(InstrumentationBackend.java:149)
I/TestRunner( 1790): 	at java.lang.reflect.Method.invoke(Native Method)
I/TestRunner( 1790): 	at java.lang.reflect.Method.invoke(Method.java:372)
I/TestRunner( 1790): 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
I/TestRunner( 1790): 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
I/TestRunner( 1790): 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
I/TestRunner( 1790): 	at junit.framework.TestCase.runBare(TestCase.java:134)
I/TestRunner( 1790): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
I/TestRunner( 1790): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
I/TestRunner( 1790): 	at junit.framework.TestResult.run(TestResult.java:118)
I/TestRunner( 1790): 	at junit.framework.TestCase.run(TestCase.java:124)
I/TestRunner( 1790): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
I/TestRunner( 1790): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
I/TestRunner( 1790): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
I/TestRunner( 1790): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
I/TestRunner( 1790): ----- end exception -----
I/TestRunner( 1790): finished: testHook(sh.calaba.instrumentationbackend.InstrumentationBackend)
I/ActivityManager(  358): Force stopping <my_package> appid=10054 user=0: finished inst
I/ActivityManager(  358): Killing 1790:<my_package>/u0a54 (adj 0): stop <my_package>
I/WindowState(  358): WIN DEATH: Window{2b610964 u0 <my_package/my_activity>}
W/ActivityManager(  358): Force removing ActivityRecord{276f56d2 u0 <my_package/my_activity> t4}: app died, no saved state
I/ActivityManager(  358): Activity reported stop, but no longer stopping: ActivityRecord{2169875c u0 com.android.launcher/com.android.launcher2.Launcher t3}
W/ActivityManager(  358): Spurious death for ProcessRecord{37971882 1790:<my_package>/u0a54}, curProc for 1790: null
D/gralloc_goldfish( 1820): Emulator without GPU emulation detected.
D/gralloc (   53): Registering a buffer in the process that created it. This may cause memory ordering problems.
E/libEGL  (   53): called unimplemented OpenGL ES API
```

Here's the error output from circle:
```
2015-05-14 16:23:47 - First scenario in feature - reinstalling apps
2015-05-14 16:23:50 - connected_devices: ["emulator-5554"]
2015-05-14 16:23:50 - Persistently allocated port 34777 to emulator-5554
2015-05-14 16:23:50 - "/usr/local/android-sdk-linux/platform-tools/adb" -s emulator-5554 forward tcp:34777 tcp:7102
2015-05-14 16:23:50 - 
2015-05-14 16:23:50 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:23:50 - Uninstalling: <my_test_package>
2015-05-14 16:23:53 - Failure [DELETE_FAILED_INTERNAL_ERROR]

2015-05-14 16:23:55 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:23:56 - Uninstalling: <my_package>
2015-05-14 16:23:58 - Failure [DELETE_FAILED_INTERNAL_ERROR]

2015-05-14 16:24:00 - Installing: test_servers/d6dcaa802d4a1352d10f51a9813be557_0.5.8.apk
1272 KB/s (563472 bytes in 0.432s)
2015-05-14 16:24:41 - 	pkg: /data/local/tmp/d6dcaa802d4a1352d10f51a9813be557_0.5.8.apk

Success

2015-05-14 16:24:41 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:24:43 - Installing: /home/ubuntu/<directory>/calabash.apk
1360 KB/s (3951469 bytes in 2.837s)
2015-05-14 16:26:45 - 	pkg: /data/local/tmp/calabash.apk

Success

2015-05-14 16:26:45 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:26:48 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:26:48 - Trying to find launchable activity
2015-05-14 16:26:48 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:26:48 - Found launchable activity '<my_activity>'
2015-05-14 16:26:48 - Found tools directory at '/usr/local/android-sdk-linux/build-tools/22.0.1'
2015-05-14 16:26:48 - Starting test server using:
2015-05-14 16:26:48 - "/usr/local/android-sdk-linux/platform-tools/adb" -s emulator-5554 shell am instrument -e target_package <my_package> -e main_activity <my_activity> -e test_server_port 7102 -e class sh.calaba.instrumentationbackend.InstrumentationBackend <my_test_package>/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
2015-05-14 16:26:51 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:26:52 - Checking if instrumentation backend is ready
2015-05-14 16:26:52 - Is app running? true
2015-05-14 16:26:52 - Instrumentation backend not yet ready
2015-05-14 16:26:55 - Checking if instrumentation backend is ready
2015-05-14 16:26:55 - Is app running? true
2015-05-14 16:26:55 - Instrumentation backend not yet ready
2015-05-14 16:26:58 - Checking if instrumentation backend is ready
2015-05-14 16:26:58 - Is app running? true
2015-05-14 16:26:58 - Instrumentation backend not yet ready
2015-05-14 16:27:01 - Checking if instrumentation backend is ready
2015-05-14 16:27:02 - Is app running? true
2015-05-14 16:27:02 - Instrumentation backend not yet ready
2015-05-14 16:27:05 - Checking if instrumentation backend is ready
2015-05-14 16:27:05 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:05 - Is app running? false
2015-05-14 16:27:05 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:08 - Checking if instrumentation backend is ready
2015-05-14 16:27:08 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:08 - Is app running? false
2015-05-14 16:27:08 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:11 - Checking if instrumentation backend is ready
2015-05-14 16:27:11 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:11 - Is app running? false
2015-05-14 16:27:11 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:14 - Checking if instrumentation backend is ready
2015-05-14 16:27:14 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:14 - Is app running? false
2015-05-14 16:27:14 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:17 - Checking if instrumentation backend is ready
2015-05-14 16:27:17 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:17 - Is app running? false
2015-05-14 16:27:17 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:20 - Checking if instrumentation backend is ready
2015-05-14 16:27:20 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:20 - Is app running? false
2015-05-14 16:27:20 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
  Unable to make connection to Calabash Test Server at http://127.0.0.1:34777/
  Please check the logcat output for more info about what happened
   (RuntimeError)
  /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/calabash-android-0.5.8/lib/calabash-android/operations.rb:640:in `rescue in start_test_server_in_background'
  /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/calabash-android-0.5.8/lib/calabash-android/operations.rb:623:in `start_test_server_in_background'
  /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/calabash-android-0.5.8/lib/calabash-android/operations.rb:136:in `start_test_server_in_background'
  /home/ubuntu/<my_directory>/features/support/app_life_cycle_hooks.rb:5:in `Before'
    When I press "Next"           # calabash-android-0.5.8/lib/calabash-android/steps/press_button_steps.rb:17
    Then I see "Next"             # calabash-android-0.5.8/lib/calabash-android/steps/assert_steps.rb:5
2015-05-14 16:27:20 - java -jar /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/calabash-android-0.5.8/lib/calabash-android/lib/screenshotTaker.jar emulator-5554 "screenshot_0.png"
2015-05-14 16:27:21 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2015-05-14 16:27:21 - Server not responding. Moving on.

Failing Scenarios:
cucumber features/my_first.feature:3 # Scenario: <First scenario>

1 scenario (1 failed)
2 steps (2 skipped)

3m33.995s calabash-android run "`pwd`/calabash.apk" -v returned exit code 1
```
Any help or ideas of other things to try would be greatly appreciated.

**Comment by agustinbala** [comment]
Any news about this? Could you fix this error?

**Comment by Gregliest** [comment]
Nope, nothing.

**Comment by TobiasRoikjer** [comment]
@Gregliest This is very strange. Is your CI environment talking directly to the device over ADB?

**Comment by Gregliest** [comment]
The CI environment is pointing to its internal emulator.

**Comment by TobiasRoikjer** [comment]
@Gregliest did you solve this?

**Comment by Gregliest** [comment]
Nope, couldn't get it to work.

**Comment by TobiasRoikjer** [comment]
@Gregliest is main_activity set to the correct value? Try updating calabash-android and pass no value to the test-server
