### ISSUE TITLE
Exception trying to submit APK to Xamarin Test Cloud

### ISSUE THREAD

**Issue by topgenorth** [calabash/calabash-android#576]
Trying to submit an APK created using Android Studio to Xamarin Test Cloud. Running tests locally against the simulator work fine. Using calabash-android 0.5.9 and xamarin-test-cloud 1.1.1 on OS X Yosemite.  Here is the output when I try to submit:

	$ ruby -v
	ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]

	$ test-cloud submit app-debug.apk < MY_API_KEY> --devices 02e0886c --series "master" --locale "en_US" --user tom.opgenorth@xamarin.com

	### Checking for Gemfile ###
	2015-05-22 14:44:38 -0600 
	2015-05-22 14:44:38 -0600 Gemfile missing.
	2015-05-22 14:44:38 -0600 You must provide a Gemfile in your workspace.
	2015-05-22 14:44:38 -0600 A Gemfile must describe your dependencies and their versions
	2015-05-22 14:44:38 -0600 See: http://gembundler.com/v1.3/gemfile.html
	2015-05-22 14:44:38 -0600 
	2015-05-22 14:44:38 -0600 Warning proceeding with default Gemfile.
	2015-05-22 14:44:38 -0600 It is strongly recommended that you create a custom Gemfile.
	/Users/tom/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2098:in `raise_if_conflicts': Unable to activate calabash-android-0.5.9, because retriable-2.0.2 conflicts with retriable (< 1.5, >= 1.3.3.1) (Gem::ConflictError)
		from /Users/tom/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1286:in `activate'
		from /Users/tom/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems.rb:196:in `rescue in try_activate'
		from /Users/tom/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
		from /Users/tom/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
		from /Users/tom/.rbenv/versions/2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/lib/xamarin-test-cloud/cli.rb:636:in `calabash_android_version'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/lib/xamarin-test-cloud/cli.rb:517:in `block in copy_default_gemfile'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/lib/xamarin-test-cloud/cli.rb:514:in `open'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/lib/xamarin-test-cloud/cli.rb:514:in `copy_default_gemfile'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/lib/xamarin-test-cloud/cli.rb:404:in `submit_test_job'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/lib/xamarin-test-cloud/cli.rb:280:in `submit'
		from /Users/tom/.calabash/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
		from /Users/tom/.calabash/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
		from /Users/tom/.calabash/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
		from /Users/tom/.calabash/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
		from /Users/tom/.calabash/gems/xamarin-test-cloud-1.1.1/bin/test-cloud:7:in `<top (required)>'
		from /Users/tom/.rbenv/versions/2.1.2/bin/test-cloud:23:in `load'
		from /Users/tom/.rbenv/versions/2.1.2/bin/test-cloud:23:in `<main>'

Is it now mandatory to have a Gemfile for `calabash-android`?

**Comment by topgenorth** [comment]
Just created a Gemfile and used Bundler to submit the test. XTC upload succeeded.
