### ISSUE TITLE
helpers.rb:180:in `extract_signature_algorithm_name': No signature algorithm names found: (RuntimeError)

### ISSUE THREAD

**Issue by if1else0** [calabash/calabash-android#580]
I upgrade calabash-android to 0.5.9, when i want to run the test scripts, it displayed the error messages in console like this:
calabash-android run AUT/eln_base-update-release9.9.9_debug.apk -p android features/qa_questionsadd.feature -v
2015-06-01 13:43:56 - JDK found on PATH.
2015-06-01 13:43:56 - JDK found at: /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
2015-06-01 13:43:56 - Android SDK found at: /Users/aaronyang/Library/Android/sdk
No test server found for this combination of app and calabash version. Recreating test server.
2015-06-01 13:43:56 - Signature files:
2015-06-01 13:43:56 - /var/folders/v1/z20mv1h506z7gg_s4gds2c1h0000gn/T/d20150601-1142-5blrjq/META-INF/ANDROIDD.RSA
2015-06-01 13:43:56 - "/usr/bin/keytool" -v -printcert -J"-Dfile.encoding=utf-8" -file "/var/folders/v1/z20mv1h506z7gg_s4gds2c1h0000gn/T/d20150601-1142-5blrjq/META-INF/ANDROIDD.RSA"
2015-06-01 13:43:56 - MD5 fingerprint for signing cert (/Users/aaronyang/Documents/nd/bdd_dev_branch/AUT/eln_base-update-release9.9.9_debug.apk): C7:57:FD:18:25:7A:2E:D1:54:01:9F:97:4E:7F:3D:63
2015-06-01 13:43:56 - /Users/aaronyang/Documents/nd/bdd_dev_branch/AUT/eln_base-update-release9.9.9_debug.apk was signed with a certificate with fingerprint C7:57:FD:18:25:7A:2E:D1:54:01:9F:97:4E:7F:3D:63
2015-06-01 13:43:56 - Reading keystore data from keystore file '/Users/aaronyang/.android/debug.keystore'
2015-06-01 13:43:56 - "/usr/bin/keytool" -list -v -alias androiddebugkey -keystore /Users/aaronyang/.android/debug.keystore -storepass android "-J"-Dfile.encoding=utf-8""
2015-06-01 13:43:56 - Key store data:
2015-06-01 13:43:56 - 别名: androiddebugkey
创建日期: 2015-5-4
条目类型: PrivateKeyEntry
证书链长度: 1
证书[1]:
所有者: CN=Android Debug, O=Android, C=US
发布者: CN=Android Debug, O=Android, C=US
序列号: 7b72b2f7
有效期开始日期: Mon May 04 18:07:25 CST 2015, 截止日期: Wed Apr 26 18:07:25 CST 2045
证书指纹:
	 MD5: F8:4C:3E:59:5D:72:73:16:4D:8B:A5:A1:46:95:AC:0E
	 SHA1: 01:38:EB:37:8E:9C:B5:26:E4:0D:16:1C:9C:92:E0:AD:B9:47:23:C6
	 SHA256: FF:43:B9:3A:5A:CD:4E:EA:8E:C7:8A:BE:15:14:E2:39:32:A8:5F:B4:8B:BA:F3:38:97:90:86:5D:39:DD:2A:12
	 签名算法名称: SHA256withRSA
	 版本: 3

扩展: 

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 14 CA 5C EE E2 9B 8C DD   47 EA CC EC 22 B2 D0 89  ..\.....G..."...
0010: BC C2 D4 31                                        ...1
]
]

/Users/aaronyang/.calabash/gems/calabash-android-0.5.9/lib/calabash-android/helpers.rb:180:in `extract_signature_algorithm_name': No signature algorithm names found: (RuntimeError)
 别名: androiddebugkey
创建日期: 2015-5-4
条目类型: PrivateKeyEntry
证书链长度: 1
证书[1]:
所有者: CN=Android Debug, O=Android, C=US
发布者: CN=Android Debug, O=Android, C=US
序列号: 7b72b2f7
有效期开始日期: Mon May 04 18:07:25 CST 2015, 截止日期: Wed Apr 26 18:07:25 CST 2045
证书指纹:
	 MD5: F8:4C:3E:59:5D:72:73:16:4D:8B:A5:A1:46:95:AC:0E
	 SHA1: 01:38:EB:37:8E:9C:B5:26:E4:0D:16:1C:9C:92:E0:AD:B9:47:23:C6
	 SHA256: FF:43:B9:3A:5A:CD:4E:EA:8E:C7:8A:BE:15:14:E2:39:32:A8:5F:B4:8B:BA:F3:38:97:90:86:5D:39:DD:2A:12
	 签名算法名称: SHA256withRSA
	 版本: 3

扩展: 

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 14 CA 5C EE E2 9B 8C DD   47 EA CC EC 22 B2 D0 89  ..\.....G..."...
0010: BC C2 D4 31                                        ...1
]
]

	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/lib/calabash-android/java_keystore.rb:42:in `initialize'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/lib/calabash-android/java_keystore.rb:72:in `new'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/lib/calabash-android/java_keystore.rb:72:in `read_keystore_with_default_password_and_alias'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/lib/calabash-android/java_keystore.rb:91:in `get_keystores'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/bin/calabash-android-build.rb:5:in `calabash_build'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/lib/calabash-android/helpers.rb:100:in `build_test_server_if_needed'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/bin/calabash-android-run.rb:16:in `calabash_run'
	from /Users/aaronyang/.calabash/gems/calabash-android-0.5.9/bin/calabash-android:85:in `<top (required)>'
	from /Users/aaronyang/.calabash/bin/calabash-android:23:in `load'
	from /Users/aaronyang/.calabash/bin/calabash-android:23:in `<main>'

**Comment by TobiasRoikjer** [comment]
@if1else0 Upgrading to 0.5.10.pre1 should fix this issue.

**Comment by TobiasRoikjer** [comment]
@if1else0 0.5.10.pre2, sorry, not 0.5.10.pre1

**Comment by if1else0** [comment]
@TobiasRoikjer  it works fine on version 0.5.10.pre2, thanks for quick response.
