### ISSUE TITLE
TextView not queryable when hidden in a scrollview

### ISSUE THREAD

**Issue by scottgoldwater** [calabash/calabash-android#600]
I would like to be able to scroll down to a textview off screen within a scrollview and be able to query it. 

To demonstrate my problem I have made the following layout:

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent" android:layout_height="match_parent"
    android:orientation="vertical">
    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical"
        android:layout_margin="@dimen/small_margin"
        android:id="@+id/scrollView">
        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingTop="1000dp"
            android:paddingBottom="300dp"
            android:text="@string/hidden_text"
            android:id="@+id/hidden_text"/>
    </ScrollView>
</LinearLayout>
```

It is just a static layout fragment with no logic. The fragment contains a scrollview with a textview 1000dp downwards. I understand that if an element is off screen it does not show up in a query("*") command, however when I scroll down to it myself I expected to be able to query it. 

I also tried this command in the console:

```ruby
scroll_to("TextView id:'hidden_text'")
```

I got this output: 

```html
Embed is a Cucumber method and is not available in this console.
Calabash::Android::WaitHelpers::WaitError: Timeout waiting for elements: all TextView id:'hidden_text'
	from /Users/scott/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.5.12/lib/calabash-android/wait_helpers.rb:65:in `screenshot_and_retry'
	from /Users/scott/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.5.12/lib/calabash-android/wait_helpers.rb:47:in `rescue in wait_for'
	from /Users/scott/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.5.12/lib/calabash-android/wait_helpers.rb:38:in `wait_for'
	from /Users/scott/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.5.12/lib/calabash-android/wait_helpers.rb:97:in `wait_for_elements_exist'
	from /Users/scott/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.5.12/lib/calabash-android/wait_helpers.rb:88:in `wait_for_element_exists'
	from /Users/scott/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.5.12/lib/calabash-android/operations.rb:1053:in `scroll_to'
	from (irb):29
	from /Users/scott/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

Do certain commands only work as cucumber tests. Will using 
```ruby
scroll_to("TextView id:'hidden_text'")
```
as part of a ruby cucumber test give me the results I want?

**Comment by AAverin** [comment]
That's the way calabash works. It queries only things that are visible on the screen

**Comment by TobiasRoikjer** [comment]
If `scroll_to` does not work, try panning or scrolling until an element is shown.
