### ISSUE TITLE
NullPointerException  at prepareWebView

### ISSUE THREAD

**Issue by hansinator85** [calabash/calabash-android#602]
I have an irregular occuring issue using the webview.

Currently using calabash-android **0.5.8** (will update to 0.5.12, but as far as I could see, the NPE can also occur on latest version) on emulator with **API 17**.

When the app is started, it first loads a webview.
  - When the webview contains a valid cookie from a previous session it will load the required resources in background and closes the webview when finished with the resources.
  - When the webview has no valid cookie, it will show the login screen.

So i have my login step with a wait_for that checks whether the webview (still) exists or if the login is available:
![failing ruby](https://cloud.githubusercontent.com/assets/13363817/8721276/9df66f26-2bb9-11e5-8825-afa8a5ddca75.png)

But sometimes this check fails:
![failed scenario](https://cloud.githubusercontent.com/assets/13363817/8721223/236451d8-2bb9-11e5-8efe-105f19ad468f.png)

`Just for info:
The SaveWebView extends the normal WebView and only overrides the onDestroy to really stop loading and clear up some memory as this was not correctly done in some older android versions.`

Here is the relevant logcat output from last nights run:
```
07-16 23:13:27.636 I/System.out( 5921): isDomQuery: css
07-16 23:13:27.636 W/System.err( 5921): java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:96)
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:76)
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:18)
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:51)
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:303)
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:454)
07-16 23:13:27.636 W/System.err( 5921): 	at java.lang.Thread.run(Thread.java:856)
07-16 23:13:27.636 W/System.err( 5921): Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
07-16 23:13:27.636 W/System.err( 5921): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
07-16 23:13:27.636 W/System.err( 5921): 	at java.util.concurrent.FutureTask.get(FutureTask.java:174)
07-16 23:13:27.636 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:58)
07-16 23:13:27.636 W/System.err( 5921): 	... 6 more
07-16 23:13:27.636 W/System.err( 5921): Caused by: java.lang.NullPointerException
07-16 23:13:27.646 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.actions.webview.CalabashChromeClient.prepareWebView(CalabashChromeClient.java:182)
07-16 23:13:27.646 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:63)
07-16 23:13:27.656 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:43)
07-16 23:13:27.656 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.actions.webview.QueryHelper.executeAsyncJavascriptInWebContainer(QueryHelper.java:69)
07-16 23:13:27.656 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateForWebContainer(UIQueryASTWith.java:186)
07-16 23:13:27.656 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.access$100(UIQueryASTWith.java:20)
07-16 23:13:27.656 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$MatchForViews.call(UIQueryASTWith.java:113)
07-16 23:13:27.656 W/System.err( 5921): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$MatchForViews.call(UIQueryASTWith.java:100)
07-16 23:13:27.666 W/System.err( 5921): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
07-16 23:13:27.666 W/System.err( 5921): 	at android.os.Handler.handleCallback(Handler.java:725)
07-16 23:13:27.666 W/System.err( 5921): 	at android.os.Handler.dispatchMessage(Handler.java:92)
07-16 23:13:27.666 W/System.err( 5921): 	at android.os.Looper.loop(Looper.java:137)
07-16 23:13:27.666 W/System.err( 5921): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
07-16 23:13:27.666 W/System.err( 5921): 	at java.lang.reflect.Method.invokeNative(Native Method)
07-16 23:13:27.666 W/System.err( 5921): 	at java.lang.reflect.Method.invoke(Method.java:511)
07-16 23:13:27.666 W/System.err( 5921): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
07-16 23:13:27.666 W/System.err( 5921): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
07-16 23:13:27.666 W/System.err( 5921): 	at dalvik.system.NativeStart.main(Native Method)
```

As I've analyzed from code, the given webView can definitely not be null.
See callstack:
`sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$MatchForViews.call(UIQueryASTWith.java:113)` --> **in 0.5.12 it will be line 123**
```Java
     private class MatchForViews implements Callable<Future> {
        private final Object o;
        private final int index;

        MatchForViews(Object o, int index) {
            this.o = o;
            this.index = index;
        }

        public Future call() throws Exception {
            if (o instanceof View && isDomQuery()) {
                View view = (View) o;

                Future webResult = evaluateForWebContainer(new WebContainer(view));

                if (webResult != null) {
                    return webResult;
                }
            } else if (o instanceof Map) {
                Map result = evaluateForMap((Map) o);
                if (result != null) {
                    return new CompletedFuture(result);
                }

            } else {
                Object result = evaluateForObject(o, index);
                if (result != null) {
                    return new CompletedFuture(result);
                }
            }
            return new CompletedFuture(null);
        }
    }
```

Which makes the call stable too
`sh.calaba.instrumentationbackend.query.WebContainer.evaluateAsyncJavaScript(WebContainer.java:63)`
```Java
        if (isAndroidWebView()) {
            WebView webView = (WebView) getView();

            if (Build.VERSION.SDK_INT < 19) { // < Android 4.4
                CalabashChromeClient chromeClient = CalabashChromeClient.prepareWebView(webView);
```

So lets watch:
`sh.calaba.instrumentationbackend.actions.webview.CalabashChromeClient.prepareWebView(CalabashChromeClient.java:182)`
```Java
	public static CalabashChromeClient prepareWebView(WebView webView) {
		CalabashChromeClient calabashChromeClient = new CalabashChromeClient(
				webView);
		webView.getSettings().setJavaScriptEnabled(true);
		return calabashChromeClient;
	}
```

As seen before, the webView should be fine, so the settings must be faulty here in some cases.
I don't get it how the implementation can even work in API 16 & 17 ... see different Versions for **getSettings()**:

**API 15**
```Java
    public WebSettings getSettings() {
        checkThread();
        return (mWebViewCore != null) ? mWebViewCore.getSettings() : null;
    }
```

**API 16**
```Java
    public WebSettings getSettings() {
        return null;
    }
```

**API 17**
```Java
    public WebSettings getSettings() {
        return null;
    }
```

**API 18**
```Java
    public WebSettings getSettings() {
        checkThread();
        return mProvider.getSettings();
    }
```

**API 19**
```Java
    public WebSettings getSettings() {
        checkThread();
        return mProvider.getSettings();
    }
```

**Comment by jmoody** [comment]
@hansinator85 +10 Excellent reporting!  I am going to cry... :pizza:

**Comment by TobiasRoikjer** [comment]
@hansinator85 Great issue report! Fully agree with @jmoody

**Comment by ysilyutin** [comment]
Hi all, any updates on this one? We are facing with this problem from time to time.
