### ISSUE TITLE
get_preferences gives JSON::ParserError: 757: unexpected token

### ISSUE THREAD

**Issue by mrsasha** [calabash/calabash-android#629]
Hi,

I've encountered the following error using get_preferences() in version 0.5.14 with Ruby 2.2.0:
```
irb(main):002:0> get_preferences('STMPreferences')
JSON::ParserError: 757: unexpected token at '{"key": "saved_user", "value": "{"l
astLogin":"2015-10-12T14:33:41.000Z","locale":"en_GB","timezone":"GMT","userHash
":"7f538e5fabc4e9ab6b4b9501af6d54eda22e43f6","id":0}"}'
        from c:/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:155:in 'parse'
        from c:/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:155:in 'parse'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.14/lib/
calabash-android/operations.rb:745:in 'block in get_preferences'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.14/lib/
calabash-android/operations.rb:744:in 'each'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.14/lib/
calabash-android/operations.rb:744:in 'get_preferences'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.14/lib/
calabash-android/operations.rb:170:in 'get_preferences'
        from (irb):2
        from c:/Ruby22-x64/bin/irb:11:in '<main>'
```

**Comment by philipbjorge** [comment]
I'm hitting this with the following value:
```
{"key": "App Restrictions", "value": "AAAAAA==
"}
```

Looks like it might be control characters?
http://apps.timwhitlock.info/unicode/inspect?s=%0D%0A

**Comment by rtymchyk** [comment]
Noticing this as well, with key/value that looks something like:
`{"key": "x", "value": 7f538e5fab-4e9ab6b4b95-01af6d54-eda22e43f6}` The value is not properly wrapped in quotes to be parsed as JSON.
