### ISSUE TITLE
Broken by default

### ISSUE THREAD

**Issue by iMerica** [calabash/calabash-android#639]
On a new project setup created using `calabash-android gen`, Calabash Android does not work end-to-end due to a TypeError. This is me running the example feature file using Ruby 2.2.3 and Calabash Android 0.5.14.

```
❯ cucumber Android/features/my_first.feature                                                                                                               
Feature: Login feature

  Scenario: As a valid user I can log into my app # Android/features/my_first.feature:3
  no implicit conversion of nil into String (TypeError)
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:9:in `exist?'
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:9:in `package_name'
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:112:in `uninstall_apps'
  /Users/michael/Projects/analytics-tests/Android/features/support/app_installation_hooks.rb:22:in `Before'
  no implicit conversion of nil into String (TypeError)
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:9:in `exist?'
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/helpers.rb:9:in `package_name'
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:616:in `start_test_server_in_background'
  /Users/michael/.rvm/gems/ruby-2.2.3/gems/calabash-android-0.5.14/lib/calabash-android/operations.rb:133:in `start_test_server_in_background'
  /Users/michael/Projects/analytics-tests/Android/features/support/app_life_cycle_hooks.rb:5:in `Before'
    When I press "Login"                          # calabash-android-0.5.14/lib/calabash-android/steps/press_button_steps.rb:17
    Then I see "Welcome to coolest app ever"      # calabash-android-0.5.14/lib/calabash-android/steps/assert_steps.rb:5

Failing Scenarios:
cucumber Android/features/my_first.feature:3 # Scenario: As a valid user I can log into my app

1 scenario (1 failed)
2 steps (2 skipped)
0m1.530s

```

**Comment by iMerica** [comment]
This looks like it's occurring because I'm calling Cucumber explicitly and not using  `calabash-android run`. Might be good to make `helpers.rb` introspect itself to make sure Cucumber is invoked using the custom runner instead of Cucumber proper.

**Comment by TobiasRoikjer** [comment]
@iMerica Looking at the line, it appears that the default application is not set. If you are running using cucumber, you will have to set the target application yourself using environment variables (for example from your cucumber.yml file).
