### ISSUE TITLE
App does not relaunch for second scenario on Android device with OS < 5.0

### ISSUE THREAD

**Issue by ssekhri** [calabash/calabash-android#683]
While testing an android application using calabash-android such that the feature file has more than one scenario and the setup is such that the app would relaunch for each scenario. When running the calabash-android, the app installs and runs the first scenario successfully. Then for the second scenario it closes the app and tries to launch the app again. But the app does not launch. We can actually see a flicker suggesting that the app started to launch but was killed.
This happens only on android devices with OS version less than 5.0. Tried on number of different 4.x.x devices (locally as well as on a device cloud) and result is the same.
If the same environment and the same script is ran on 5.0 or above android device the issue is not seen.
Following are the calabash logs of the issue are after running the command 'calabash-android run <apkname.apk>':
```
2016-02-02 10:21:58 - Starting test server using:
2016-02-02 10:21:58 - "/Users/username/Library/Android/sdk/platform-tools/adb" -s "0149CBF303012016" shell am instrument -e target_package app.test.myapp -e main_activity app.test.myapp.SplashActivity -e test_server_port 7102 -e class sh.calaba.instrumentationbackend.InstrumentationBackend app.test.myapp.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
2016-02-02 10:22:14 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:22:30 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:22:46 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:23:02 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:23:18 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:23:34 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:23:50 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:24:06 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:24:22 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
2016-02-02 10:24:38 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
  App did not start (RuntimeError)
  /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:638:in `block in start_test_server_in_background'
 /usr/local/lib/ruby/gems/2.2.0/gems/retriable-1.4.1/lib/retriable/retriable.rb:31:in `perform'
  /usr/local/lib/ruby/gems/2.2.0/gems/retriable-1.4.1/lib/retriable/retriable.rb:59:in `retriable'
  /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:637:in `start_test_server_in_background'
 /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:133:in `start_test_server_in_background'
 ./features/support/app_life_cycle_hooks.rb:5:in `Before'

2016-02-02 10:24:54 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
      execution expired (HTTPClient::ReceiveTimeoutError)
      /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:879:in `gets'
      /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:879:in `block in parse_header'
     /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:875:in `parse_header'
      /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:858:in `read_header'
     /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient/session.rb:667:in `get_header'
      /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1137:in `do_get_header'
      /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:1086:in `do_get_block'
    /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:887:in `block in do_request'
    /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:981:in `protect_keep_alive_disconnected'
      /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:886:in `do_request'
     /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:774:in `request'
     /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.7.1/lib/httpclient.rb:684:in `post'
    /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:448:in `make_http_request'
     /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:385:in `http'
     /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:692:in `shutdown_test_server'
     /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.5.15/lib/calabash-android/operations.rb:137:in `shutdown_test_server'
      ./features/support/app_life_cycle_hooks.rb:12:in `After'
```

**Comment by ssekhri** [comment]
Updated calabash-android to 0.6.0 to get the same results.
If it helps then following is the output from using the console:
```
$ calabash-android console myapp.apk
Starting calabash-android console...
Loading /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/irbrc
Running irb...
irb(main):001:0> reinstall_test_server
9090 KB/s (580239 bytes in 0.062s)
nil
irb(main):002:0> reinstall_apps
8733 KB/s (6008265 bytes in 0.671s)
5909 KB/s (580239 bytes in 0.095s)
nil
irb(main):003:0> start_test_server_in_background
nil
irb(main):004:0> shutdown_test_server
nil
irb(main):005:0> start_test_server_in_background
RuntimeError: App did not start
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:660:in `block in start_test_server_in_background'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:659:in `start_test_server_in_background'
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:141:in `start_test_server_in_background'
	from (irb):5
	from /usr/local/bin/irb:11:in `<main>'
irb(main):006:0> shutdown_test_server
HTTPClient::ReceiveTimeoutError: execution expired
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient/session.rb:881:in `gets'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient/session.rb:881:in `block in parse_header'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient/session.rb:877:in `parse_header'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient/session.rb:860:in `read_header'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient/session.rb:667:in `get_header'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:1144:in `do_get_header'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:1093:in `do_get_block'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:894:in `block in do_request'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:988:in `protect_keep_alive_disconnected'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:893:in `do_request'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:778:in `request'
	from /usr/local/lib/ruby/gems/2.2.0/gems/httpclient-2.5.0/lib/httpclient.rb:684:in `post'
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:470:in `make_http_request'
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:407:in `http'
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:719:in `shutdown_test_server'
	from /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.6.0/lib/calabash-android/operations.rb:145:in `shutdown_test_server'
	from (irb):6
	from /usr/local/bin/irb:11:in `<main>'irb(main):007:0> 
```

**Comment by TobiasRoikjer** [comment]
You should run `adb logcat` and look for a stacktrace in there.
