### ISSUE TITLE
First scenario often fails with 'More than one device connected' exception

### ISSUE THREAD

**Issue by SButterfly** [calabash/calabash-android#716]
Hi, I'm using calabash-android 0.6.0
And it often happens that first scenario fails with 'More than one device connected' exception, when I connect device. But actually only one device is connected!

I found this lines in logs:

```
2016-04-27 16:50:47 - connected_devices: ["* daemon not running. starting it now on port 5037 *", "* daemon started successfully *", "WE167BFCHB100099"]
2016-04-27 16:50:47 - connected_devices: ["WE167BFCHB100099"]
```

Other scenarios works perfectly. Also I found out if I call `adb devices` from terminal before calabash - everything works perfectly.

What is the reason?

Whole logs:

```
2016-04-27 16:50:44 - First time launch - reinstalling apps
2016-04-27 16:52:21 adb I   970 53150 usb_osx.cpp:259] Found vid=0e8d pid=201d serial=WE167BFCHB100099
2016-04-27 16:52:21 adb I   970 53150 usb_osx.cpp:259] 
2016-04-27 16:52:24 2016-04-27 16:50:47 - connected_devices: ["* daemon not running. starting it now on port 5037 *", "* daemon started successfully *", "WE167BFCHB100099"]
2016-04-27 16:52:24 2016-04-27 16:50:47 - connected_devices: ["WE167BFCHB100099"]
2016-04-27 16:52:24 2016-04-27 16:50:47 - "/Users/atest/android-sdk-macosx/platform-tools/adb" -s WE167BFCHB100099 forward tcp:34793 tcp:7102
2016-04-27 16:52:24 2016-04-27 16:50:47 - 
2016-04-27 16:52:24 2016-04-27 16:50:47 - Found tools directory at '/Users/atest/android-sdk-macosx/build-tools/19.1.0'
2016-04-27 16:52:24 android.util.AndroidException: INSTRUMENTATION_FAILED: com.product.dev.test/sh.calaba.instrumentationbackend.ClearAppData
2016-04-27 16:52:24     at com.android.commands.am.Am.runInstrument(Am.java:977)
2016-04-27 16:52:24     at com.android.commands.am.Am.onRun(Am.java:317)
2016-04-27 16:52:24     at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
2016-04-27 16:52:24     at com.android.commands.am.Am.main(Am.java:97)
2016-04-27 16:52:24     at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-04-27 16:52:24     at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
2016-04-27 16:52:24 2016-04-27 16:50:48 - Found tools directory at '/Users/atest/android-sdk-macosx/build-tools/19.1.0'
2016-04-27 16:52:24 2016-04-27 16:50:48 - Trying to find launchable activity
2016-04-27 16:52:24 2016-04-27 16:50:48 - Found tools directory at '/Users/atest/android-sdk-macosx/build-tools/19.1.0'
2016-04-27 16:52:24 2016-04-27 16:50:48 - Found launchable activity 'com.product.StartupActivity_'
2016-04-27 16:52:24 2016-04-27 16:50:48 - Found tools directory at '/Users/atest/android-sdk-macosx/build-tools/19.1.0'
2016-04-27 16:52:24 2016-04-27 16:50:48 - Starting test server using:
2016-04-27 16:52:24 2016-04-27 16:50:48 - "/Users/atest/android-sdk-macosx/platform-tools/adb" -s WE167BFCHB100099 shell am instrument -e target_package com.product.dev -e main_activity com.product.StartupActivity_ -e test_server_port 7102 -e class sh.calaba.instrumentationbackend.InstrumentationBackend com.product.dev.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
2016-04-27 16:52:25 android.util.AndroidException: INSTRUMENTATION_FAILED: com.product.dev.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
2016-04-27 16:52:25     at com.android.commands.am.Am.runInstrument(Am.java:977)
2016-04-27 16:52:25     at com.android.commands.am.Am.onRun(Am.java:317)
2016-04-27 16:52:25     at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
2016-04-27 16:52:25     at com.android.commands.am.Am.main(Am.java:97)
2016-04-27 16:52:25     at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
2016-04-27 16:52:25     at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
2016-04-27 16:52:43 2016-04-27 16:50:48 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:49 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:50 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:51 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:52 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:53 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:54 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:56 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:57 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43 2016-04-27 16:50:58 - It looks like your app is no longer running. 
2016-04-27 16:52:43 It could be because of a crash or because your test script shut it down.
2016-04-27 16:52:43   @delete_drives_cleanup @create_drive_before
2016-04-27 16:52:43   Scenario Outline: Can add to drive from edit mode            # ../features/AddFromEditMode.feature:8
2016-04-27 16:52:43     Given I arrive at <source_page> page                       # ../features/AddFromEditMode.feature:9
2016-04-27 16:52:43     Then I see items                                           # ../features/AddFromEditMode.feature:10
2016-04-27 16:52:43     When I long click on first item                            # ../features/AddFromEditMode.feature:11
2016-04-27 16:52:43     Then I enter edit mode                                     # ../features/AddFromEditMode.feature:12
2016-04-27 16:52:43     When I click on "Add" button                               # ../features/AddFromEditMode.feature:13
2016-04-27 16:52:43     And I choose "Add_to_drive" option                         # ../features/AddFromEditMode.feature:14
2016-04-27 16:52:43     Then I see "Add_to_drive" page                             # ../features/AddFromEditMode.feature:15
2016-04-27 16:52:43     Then I wait 5 seconds                                      # ../features/AddFromEditMode.feature:16
2016-04-27 16:52:43     Then I click on first item                                 # ../features/AddFromEditMode.feature:17
2016-04-27 16:52:43     When I click on "Add_to_drive" button                      # ../features/AddFromEditMode.feature:18
2016-04-27 16:52:43     Then I wait 5 seconds                                      # ../features/AddFromEditMode.feature:19
2016-04-27 16:52:43     Then I check items length on first drive equals "1" by API # ../features/AddFromEditMode.feature:20
2016-04-27 16:52:43 
2016-04-27 16:52:43     Examples: 
2016-04-27 16:52:43       | source_page |
2016-04-27 16:52:43       More than one device connected. Specify device serial using ADB_DEVICE_ARG (RuntimeError)
2016-04-27 16:52:43       ./features/support/app_installation_hooks.rb:61:in `Before'
2016-04-27 16:52:43       App did not start (RuntimeError)
2016-04-27 16:52:43       ./features/support/app_life_cycle_hooks.rb:32:in `Before'
2016-04-27 16:52:43       |2016-04-27 16:51:06 - Skip 'delete_drives_after' method
```

**Comment by TobiasRoikjer** [comment]
I have added an ADB call that is unparsed to ensure the ADB service is running in 0.9.0
