### ISSUE TITLE
App freeze at random step

### ISSUE THREAD

**Issue by sschoeb** [calabash/calabash-android#718]
# Setup

- Ionic App (1.3.1)
- Test scenario fails every now and then (There are successful runs!)

# Failure description

I start the test using:
`calabash-android run ./MyApp.apk  -v`

Calabash installs the app on the connected device or emulator and starts to process the given scenario. At a random moment the app seems to freeze. All the following steps fail. This usually happens before the app (or the ionic WebView?) is completely rendered. For example, some text or icons are not yet displayed. 

There are no exceptions in the WebView. Calabash reports the following error because it cannot interact with the frozen app:

```
05-03 13:40:53.728 3163-3293/? W/System.err: java.lang.RuntimeException: java.util.concurrent.TimeoutException
05-03 13:40:53.728 3163-3293/? W/System.err:     at sh.calaba.instrumentationbackend.actions.text.TextAction.execute(TextAction.java:62)
05-03 13:40:53.728 3163-3293/? W/System.err:     at sh.calaba.instrumentationbackend.Command.execute(Command.java:47)
05-03 13:40:53.729 3163-3293/? W/System.err:     at sh.calaba.instrumentationbackend.actions.HttpServer.runCommand(HttpServer.java:530)
05-03 13:40:53.729 3163-3293/? W/System.err:     at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:487)
05-03 13:40:53.729 3163-3293/? W/System.err:     at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
05-03 13:40:53.729 3163-3293/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

# Troubleshooting
It seems the problem occurs more often on slow hardware. On newer hardware like a Galaxy S6 I could never reproduce it.

I've compared the logcat output of a successful and a failing run. The follow log-statements were unique to the failing run (no idea whether they are somehow related to the issue):
```
05-03 13:40:31.195 1877-3259/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                                 
                                                 [ 05-03 13:40:31.219  1877: 1877 D/         ]
                                                 HostConnection::get() New Host Connection established 0xa29bf810, tid 1877
                                                 
                                                 
                                                 [ 05-03 13:40:31.268  1877: 3259 D/         ]
                                                 HostConnection::get() New Host Connection established 0xa29bf8e0, tid 3259
                                                 
                                                 
...
...                                                 


05-03 13:40:33.533 1877-1877/? W/InputConnectionWrapper.ICC: Timed out waiting on IInputContextCallback
05-03 13:40:33.533 1877-1877/? W/RichInputConnection: Slow InputConnection: GET_TEXT_AFTER_CURSOR took 2001 ms.   
```

**Comment by TobiasRoikjer** [comment]
@sschoeb It is very likely that your applications UIThread has frozen (and the app has become unresponsive). Therefore Calabash can't access the UIThread. If the UIThread is frozen, your user would not be able to do anything either.

**Comment by sschoeb** [comment]
Yes, this is actually what it looks like. 

Is there a chance that calabash somehow influences our app? Without calabash, we never run into such a problem!

How exactly does calabash interact with our android app?

**Comment by TobiasRoikjer** [comment]
@sschoeb How long is the string you are trying to enter?

**Comment by sschoeb** [comment]
4 signs...

But I don't think this is the problem right? As this is more or less just a super simple app with a form and a second screen (login...), I do not see the issue in my code. 

And it does not hang during an input operation, it more looks like the WebView freezes at a random point... this point can be when there is nothing there yet when the template is loaded but no JS executed yet (just see the plain template...) or between any step. It can even happen on the second screen.

So my question remains: How exactly does calabash interact with our android app? Is there any chance that it somehow influences the behaviour of the underlying WebView?

**Comment by TobiasRoikjer** [comment]
The server is open source, so you can see exactly what calabash does here. https://github.com/calabash/calabash-android-server

We try to fully replicate how a keyboard would interact with the app. What happens if you try to enter text/select things manually?
