### ISSUE TITLE
Run Time Error - calabash android version 0.7.2 (Intermittent)

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#719]
Hi, 

  I often getting an error says `map webview css:'#xxxxx', query failed because: java.util.concurrent.ExecutionException: java.lang.NullPointerException`. But this error doesn't happen every time on running the same feature. Reproduction rate is about 1/5.

fails for this command - `wait_for(:timeout => 120) { element_exists("webview css:'"+element+"'") }`

Calabash android version used is 0.7.2. I have also added the calabash logs below. Please help me to find whats causing this. Thanks

```java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timeout while waiting for value
at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:67)
at sh.calaba.instrumentationbackend.query.ast.evaluation.UIQueryEvaluationStep.step(UIQueryEvaluationStep.java:40)
at sh.calaba.instrumentationbackend.query.ast.evaluation.QueryEvaluator.evaluateQueryForPath(QueryEvaluator.java:19)
at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:52)
at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:16)
at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:68)
at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:308)
at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.util.concurrent.TimeoutException: Timeout while waiting for value
at sh.calaba.instrumentationbackend.actions.webview.CalabashChromeClient$WebFuture.get(CalabashChromeClient.java:456)
at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$1.call(UIQueryASTWith.java:200)
at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$1.call(UIQueryASTWith.java:197)
at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:64)```

**Comment by TobiasRoikjer** [comment]
You should upgrade to 0.7.3
