### ISSUE TITLE
Install not possible on x86 emulator

### ISSUE THREAD

**Issue by sschoeb** [calabash/calabash-android#724]
I try to automate my calabash-tests using a TeamCity build server.

Everything is running inside a docker-container.
A x86 emulator is up and running (using kvm)

I execute the following command:
`calabash-android run ./MyApp.apk -p android -v`

This works when I do have a real device connected instead of a running emulator. On the emulator it crashes with the following log: 

```
2016-05-20 13:10:56 - Trying to find launchable activity
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to '/etc/android/sdk'
DEBUG: Set aapt path to '/etc/android/sdk/build-tools/23.0.1/aapt'
DEBUG: Set zipalign path to '/etc/android/sdk/build-tools/23.0.1/zipalign'
DEBUG: Set adb path to '/etc/android/sdk/platform-tools/adb'
DEBUG: Set android jar path to '/etc/android/sdk/platforms/android-23/android.jar'
DEBUG: Java SDK location set to ''
DEBUG: Found java on PATH
DEBUG: Set java path to '/usr/bin/java'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '/usr/bin/keytool'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '/usr/bin/jarsigner'
2016-05-20 13:10:56 - Found launchable activity 'ch.myapp.MainActivity'
2016-05-20 13:10:56 - /usr/local/bin/ruby -S cucumber -p android -v MAIN_ACTIVITY=ch.myapp.MainActivity APP_PATH="/home/teamcity/agent/work/9f9deea73e945917/www/ui_tests/android/MyApp.apk" TEST_APP_PATH="test_servers/d3e62edd66b1cb425200fa72adc1181e_0.7.3.apk"
Code:
  * features/support/env.rb
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to '/etc/android/sdk'
DEBUG: Set aapt path to '/etc/android/sdk/build-tools/23.0.1/aapt'
DEBUG: Set zipalign path to '/etc/android/sdk/build-tools/23.0.1/zipalign'
DEBUG: Set adb path to '/etc/android/sdk/platform-tools/adb'
DEBUG: Set android jar path to '/etc/android/sdk/platforms/android-23/android.jar'
DEBUG: Java SDK location set to ''
DEBUG: Found java on PATH
DEBUG: Set java path to '/usr/bin/java'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '/usr/bin/keytool'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '/usr/bin/jarsigner'
  * features/support/android_setup.rb
  * features/support/ios_dry_run.rb
  * features/support/ios_launch.rb
  * features/support/teamcity_formatter.rb
  * features/steps/myapp_steps.rb

Features:
  * features/sample.feature

Using the android profile...
Feature: Login feature

2016-05-20 13:10:56 - First scenario in feature - reinstalling apps
2016-05-20 13:10:56 - connected_devices: ["emulator-5554"]
2016-05-20 13:10:56 - "/etc/android/sdk/platform-tools/adb" -s emulator-5554 forward tcp:34777 tcp:7102
2016-05-20 13:10:56 -
2016-05-20 13:10:56 - Uninstalling: ch.myapp.test
2016-05-20 13:10:56 - Aborted
2016-05-20 13:10:57 - Uninstalling: ch.myapp
2016-05-20 13:10:57 - Aborted
2016-05-20 13:10:57 - Installing: test_servers/d3e62edd66b1cb425200fa72adc1181e_0.7.3.apk
4212 KB/s (585965 bytes in 0.135s)
2016-05-20 13:10:57 - Aborted
  Scenario: <ScenarioName> # features/sample.feature:3
  ch.myapp.test did not get installed. Reason: 'Aborted '. Aborting! (RuntimeError)
  ./features/support/android_setup.rb:22:in `Before'
  Will not start test server because of previous failures. (RuntimeError)
  ./features/support/android_setup.rb:34:in `Before'
    Given Die App ist geladen                                                                        # features/steps/myapp_steps.rb:1
    // ... all the steps... 
2016-05-20 13:10:58 - java -jar /usr/local/lib/ruby/gems/2.2.0/gems/calabash-android-0.7.3/lib/calabash-android/lib/screenshotTaker.jar emulator-5554 "screenshot_0.png"
2016-05-20 13:10:59 - It looks like your app is no longer running.
It could be because of a crash or because your test script shut it down.
2016-05-20 13:10:59 - Server not responding. Moving on.

Failing Scenarios:
cucumber -p android features/sample.feature:3 # Scenario: <ScenarioName>

1 scenario (1 failed)
8 steps (8 skipped)

```

Here is the android_setup.rb
```
if ENV['PLATFORM'] == 'android'
  require 'calabash-android/management/app_installation'
  require 'calabash-android/management/adb'
    require 'calabash-android/operations'

  AfterConfiguration do |config|
    FeatureMemory.feature = nil
  end

  Before do |scenario|
    scenario = scenario.scenario_outline if scenario.respond_to?(:scenario_outline)

    feature = scenario.feature
    if FeatureMemory.feature != feature || ENV['RESET_BETWEEN_SCENARIOS'] == '1'
      if ENV['RESET_BETWEEN_SCENARIOS'] == '1'
        log 'New scenario - reinstalling apps'
      else
        log 'First scenario in feature - reinstalling apps'
      end

      uninstall_apps
      install_app(ENV['TEST_APP_PATH'])
      install_app(ENV['APP_PATH'])
      FeatureMemory.feature = feature
      FeatureMemory.invocation = 1
    else
      FeatureMemory.invocation += 1
    end
  end

  FeatureMemory = Struct.new(:feature, :invocation).new

   Before do |scenario|
      start_test_server_in_background
    end

    After do |scenario|
      if scenario.failed?
        screenshot_embed
      end
      shutdown_test_server
    end
end

```

**Comment by TobiasRoikjer** [comment]
The application is probably not built for an x86 architecture.

**Comment by sschoeb** [comment]
The application is definitely built for x86. Is there any chance to get more information about the problem?

`Reason: 'Aborted '. Aborting! (RuntimeError)`

This message does not help that much...

**Comment by TobiasRoikjer** [comment]
This is outside the scope of calabash. This is a general Android/ADB issue. I suggest searching for answers for that error message. For example here http://stackoverflow.com/a/32103016/4547279
