### ISSUE TITLE
certificate verify failed (RestClient::SSLCertificateNotVerified)

### ISSUE THREAD

**Issue by kelvinlow** [calabash/calabash-android#732]
When I am trying to submit my APK when
`test-cloud submit <my.apk> <myID> --devices 0ef9c8b5 --series "master" --locale "zh_TW" --user <myUsername>`

and this is what I get:
`/Users/Kelvin/.calabash/sandbox/Gems/gems/rest-client-1.8.0/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /Users/Kelvin/.calabash/sandbox/Gems/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /Users/Kelvin/.calabash/sandbox/Gems/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /Users/Kelvin/.calabash/sandbox/Gems/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'`

How do I fixed this problem? Thank you

**Comment by jmoody** [comment]
@kelvinlow 

This is actually an issue with the test-cloud-command-line tool which is a closed source repository.

I see you are using the calabash-sandbox - excellent.

Please try the following.

### Update your sandbox.

```
# If you are in a sandbox, exit.
[calabash-sandbox] $ exit

$ calabash-sandbox update
```

### Force xamarin-test-cloud 2.0.0.pre5

#### Without bundler

`gem` use the highest versioned, non pre-release installed gem.  To use a pre-release, you must uninstall all other versions of a gem.

```
$ calabash-sandbox

# You should see 2.0.0.pre5 and 1.1.2
[calabash-sandbox] $ gem list xamarin-test-cloud

# Uninstall 1.1.2
[calabash-sandbox] $ gem uninstall xamarin-test-cloud --version 1.1.2

# Try submitting again
[calabash-sandbox] $ test-cloud submit ...
```

#### With bundler (recommended)

```
# Update your Gemfile to use 2.0.0.pre5
gem "xamarin-test-cloud", "2.0.0.pre5"

$ calabash-sandbox
[calabash-sandbox] $ bundle update
[calabash-sandbox] $ bundle exec test-cloud submit ...
```
