### ISSUE TITLE
Undefined Method `+' for nil:NilClass 

### ISSUE THREAD

**Issue by kylestenglineidt** [calabash/calabash-android#734]
I have installed calabash-android for Ubuntu.
No matter what the steps are I keep getting this error

 ```
Scenario: As a valid user I can log into my app                      # features/my_first.feature:3
  undefined method `+' for nil:NilClass (NoMethodError)
  ./features/support/app_installation_hooks.rb:19:in `Before'
  undefined method `+' for nil:NilClass (NoMethodError)
  ./features/support/app_life_cycle_hooks.rb:5:in `Before'
```

I have completely commented out the before step within app_life_cycle as well as app_installation, but still get the above error. I don't believe the error is in the hooks, because even when they are commented out, I still get the error. I have looked online and haven't found any answers in regards to this error. 
According to the docs, I have all the necessary installations and configurations, but still getting this error. 
If my steps are empty, I don't get the error and the step passes, but if I have calabash logic in my step, it throws the above error, no matter what logic is inserted.

```
Given(/^I am on the Login page$/) do
end
```
 ^ this doesn't throw an error

 ```
When(/^I press "([^"]*)" button$/) do |login|
   byebug
   tap_when_element_exists("android.widget.Button {text CONTAINS[c] '#{login}'}")
 end
```
^ but this one does.
Thank you for having a look and I appreciate your time.

**Comment by TobiasRoikjer** [comment]
The contents of   ./features/support/app_installation_hooks.rb can be anything. Please post the contents

**Comment by kylestenglineidt** [comment]
**app_installation_hooks.rb**

```
require 'calabash-android/management/app_installation'
require 'byebug'
   
   AfterConfiguration do |config|
     FeatureMemory.feature = nil
   end
   
   Before do |scenario|
     scenario = scenario.scenario_outline if scenario.respond_to?(:scenario_outline)
  
     feature = scenario.feature
     if FeatureMemory.feature != feature || ENV['RESET_BETWEEN_SCENARIOS'] == '1'
      if ENV['RESET_BETWEEN_SCENARIOS'] == '1'
        log 'New scenario - reinstalling apps'
      else
        log 'First scenario in feature - reinstalling apps'
      end
  
      uninstall_apps
      install_app(ENV['TEST_APP_PATH'])
      install_app(ENV['APP_PATH'])
      FeatureMemory.feature = feature
      FeatureMemory.invocation = 1
    else
      FeatureMemory.invocation += 1
  end
end
 
FeatureMemory = Struct.new(:feature, :invocation).new
```

**app_life_cycle_hooks.rb**

 ```
require 'calabash-android/management/adb'
 require 'calabash-android/operations'
   
   Before do |scenario|
     start_test_server_in_background
   end
   
   After do |scenario|
     if scenario.failed?
     screenshot_embed
   end
    shutdown_test_server
  end

```

**Comment by TobiasRoikjer** [comment]
Alright. Please post the full stacktrace from Ruby, you can tell Cucumber to print the full stack trace.

**Comment by kylestenglineidt** [comment]
Hi Tobias,
Is this what you're asking for?
```
/home/vagrant/.rvm/gems/ruby-2.1.2/gems/calabash-android-0.7.3/lib/calabash-android/operations.rb:610:in `connected_devices'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/calabash-android-0.7.3/lib/calabash-android/operations.rb:576:in `default_serial'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/calabash-android-0.7.3/lib/calabash-android/operations.rb:291:in `initialize'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/calabash-android-0.7.3/lib/calabash-android/operations.rb:69:in `new'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/calabash-android-0.7.3/lib/calabash-android/operations.rb:69:in `default_device'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/calabash-android-0.7.3/lib/calabash-android/operations.rb:122:in `uninstall_apps'
  /home/vagrant/trunkmon-mobile-app-testing/features/support/app_installation_hooks.rb:19:in `block in <top (required)>'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/rb_support/rb_hook.rb:15:in `invoke'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/runtime/before_hooks.rb:21:in `block (2 levels) in before_hooks'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `call'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/action.rb:23:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:31:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:26:in `test_step'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/step.rb:16:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `each'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `call'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `call'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:16:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:104:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:51:in `execute'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:33:in `around_hook'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `call'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `call'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/filters/quit.rb:11:in `test_case'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/runtime.rb:68:in `run!'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/lib/cucumber/cli/main.rb:32:in `execute!'
  /home/vagrant/.rvm/gems/ruby-2.1.2/gems/cucumber-2.3.3/bin/cucumber:8:in `<top (required)>'
  /home/vagrant/.rvm/gems/ruby-2.1.2/bin/cucumber:23:in `load'
  /home/vagrant/.rvm/gems/ruby-2.1.2/bin/cucumber:23:in `<main>'
  undefined method `+' for nil:NilClass (NoMethodError)
  ./features/support/app_installation_hooks.rb:23:in `Before'
  undefined method `+' for nil:NilClass (NoMethodError)
  ./features/support/app_life_cycle_hooks.rb:5:in `Before'

```

**Comment by TobiasRoikjer** [comment]
@kylestenglineidt What is the result of running `adb devices` in your shell?

**Comment by kylestenglineidt** [comment]
$ adb devices 

```
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
List of devices attached

```

**Comment by TobiasRoikjer** [comment]
@kylestenglineidt The error message is obviously wrong, but Calabash expects a device to be connected. That device should appear in that list

**Comment by kylestenglineidt** [comment]
@TobiasRoikjer Ok.  
As far as debugging the error, what would you suggest? I've tried byebug within most of the file, but haven't had much luck narrowing it down. I'm simply out of ideas.

**Comment by TobiasRoikjer** [comment]
@kylestenglineidt Did you try running Calabash with a device connected?

**Comment by TobiasRoikjer** [comment]
That is, visible on ADB

**Comment by kylestenglineidt** [comment]
That did the trick! 
Thank you very much, @TobiasRoikjer! 

Closing the issue.
