### ISSUE TITLE
 App did not start (RuntimeError) after updating to 0.8.0.pre2

### ISSUE THREAD

**Issue by kristinaste** [calabash/calabash-android#750]
After I saw your post on calabash-android Google group, I've decided to give it a try to 0.8.0.pre2. Unfortunately,  all my tests fail at run after upgrading to the new version: 

```
MacBook-Pro:calabash kristinaste$ rake android:run_smoke[en]
Ejecutando el conjunto de pruebas principales, smoke testbuild/MyApp-release-test-2.3.4.1.aaa8966.20160704.0956.apk
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to '/Users/kristinaste/Library/Android/sdk/'
DEBUG: Set aapt path to '/Users/kristinaste/Library/Android/sdk/build-tools/21.1.2/aapt'
DEBUG: Set zipalign path to '/Users/kristinaste/Library/Android/sdk/build-tools/21.1.2/zipalign'
DEBUG: Set adb path to '/Users/kristinaste/Library/Android/sdk/platform-tools/adb'
DEBUG: Set android jar path to '/Users/kristinaste/Library/Android/sdk/platforms/android-23/android.jar'
DEBUG: Setting Java SDK location to $JAVA_HOME
DEBUG: Java SDK location set to '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home'
DEBUG: Found java on PATH
DEBUG: Set java path to '/usr/bin/java'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '/usr/bin/keytool'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '/usr/bin/jarsigner'
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to '/Users/kristinaste/Library/Android/sdk/'
DEBUG: Set aapt path to '/Users/kristinaste/Library/Android/sdk/build-tools/21.1.2/aapt'
DEBUG: Set zipalign path to '/Users/kristinaste/Library/Android/sdk/build-tools/21.1.2/zipalign'
DEBUG: Set adb path to '/Users/kristinaste/Library/Android/sdk/platform-tools/adb'
DEBUG: Set android jar path to '/Users/kristinaste/Library/Android/sdk/platforms/android-23/android.jar'
DEBUG: Setting Java SDK location to $JAVA_HOME
DEBUG: Java SDK location set to '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home'
DEBUG: Found java on PATH
DEBUG: Set java path to '/usr/bin/java'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '/usr/bin/keytool'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '/usr/bin/jarsigner'
Using the android, en and common profiles...
# language: es
Característica: Puedo utilizar la lista negra

  @smoke @need_to_be_logged_in @broken_ios @clear
  Escenario: Puedo añadir a un usuario en la lista negra        # features/ajustes/lista_negra.feature:6
Starting: Intent { act=android.intent.action.MAIN cmp=eu.myapp.test.test/sh.calaba.instrumentationbackend.WakeUp }
 App did not start (RuntimeError)
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/operations.rb:690:in `block in start_test_server_in_background'
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/retry.rb:10:in `call'
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/retry.rb:10:in `block in retry'
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/retry.rb:8:in `times'
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/retry.rb:8:in `retry'
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/operations.rb:689:in `start_test_server_in_background'
 /Users/kristinaste/.rvm/gems/ruby-2.2.1/gems/calabash-android-0.8.0.pre2/lib/calabash-android/operations.rb:143:in `start_test_server_in_background'
 /Users/kristinaste/enigcalabash/features/android/support/app_life_cycle_hooks.rb:26:in `Before'
    Dado que abro la lista negra                                # features/step_definitions/ajustes_steps.rb:24
    Y añado un contacto del addressbook a la lista negra        # features/step_definitions/ajustes_steps.rb:30
    Entonces el contacto aparece como añadido en la lista negra # features/step_definitions/ajustes_steps.rb:37
```

Below I post my app_life_cycle_hooks.rb, with 0.7.3 everything works fine: 

```ruby
require 'calabash-android/operations'

def logged_in?
  sleep 3
  return element_exists("* id:'fragment_contact_listview'")
end 

INSTALLATION_STATE = {
    :installed => true
}

Before do |scenario|
  scenario_tags = scenario.source_tag_names
  if !INSTALLATION_STATE[:installed]
      uninstall_apps
      install_app(ENV['TEST_APP_PATH'])
      install_app(ENV['APP_PATH'])
      INSTALLATION_STATE[:installed] = true
  end

  if scenario_tags.include?('@clear')
    clear_app_data
  end

  wake_up
  start_test_server_in_background

    if scenario_tags.include?('@need_to_be_logged_in')
      if !logged_in? 
        steps %Q{Dado que estoy logueado en la aplicación}
      end
    end

end

After do |scenario|
  shutdown_test_server
end

```

**Comment by TobiasRoikjer** [comment]
Thank you very much for testing 0.8.0.pre2!

Could you possible send me the APK? (tobias@xamarin.com)

What device are you testing on?

**Comment by kristinaste** [comment]
Unfortunately I can not send you the apk, I work as a QA for a company and it's against NDA. 
I've tried to execute on Samsung S4 with 5.0.1 and Nexus 5 with 6.0.1, same result everywhere. There is a short blink on the screen like it intents to start, but then it throws the error. 

I've tried to remove anything unrelated with the issue from app_life_cycle_hooks.rb, leaving only 
  start_test_server_in_background  call, same: works in  0.7.3 and throws the error in 0.8.0.pre2

**Comment by TobiasRoikjer** [comment]
@kristinaste I understand. Would it be possible for you to post or send me the results of running `adb logcat` while trying to start the application?

**Comment by kristinaste** [comment]
@TobiasRoikjer Ok, I've found this in the logs while running the test. 

```
started: testHook(sh.calaba.instrumentationbackend.InstrumentationBackend)
07-13 17:19:22.418 I/TestRunner( 3931): failed: testHook(sh.calaba.instrumentationbackend.InstrumentationBackend)
07-13 17:19:22.418 I/TestRunner( 3931): ----- begin exception -----
07-13 17:19:22.418 I/TestRunner( 3931): 
07-13 17:19:22.418 I/TestRunner( 3931): java.lang.NullPointerException: package name is null
07-13 17:19:22.418 I/TestRunner( 3931): 	at android.content.ComponentName.<init>(ComponentName.java:99)
07-13 17:19:22.418 I/TestRunner( 3931): 	at android.content.Intent.setClassName(Intent.java:7093)
07-13 17:19:22.418 I/TestRunner( 3931): 	at sh.calaba.instrumentationbackend.InstrumentationBackend.setUp(InstrumentationBackend.java:70)
07-13 17:19:22.418 I/TestRunner( 3931): 	at junit.framework.TestCase.runBare(TestCase.java:132)
07-13 17:19:22.418 I/TestRunner( 3931): 	at junit.framework.TestResult$1.protect(TestResult.java:115)
07-13 17:19:22.418 I/TestRunner( 3931): 	at junit.framework.TestResult.runProtected(TestResult.java:133)
07-13 17:19:22.418 I/TestRunner( 3931): 	at junit.framework.TestResult.run(TestResult.java:118)
07-13 17:19:22.418 I/TestRunner( 3931): 	at junit.framework.TestCase.run(TestCase.java:124)
07-13 17:19:22.418 I/TestRunner( 3931): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
07-13 17:19:22.418 I/TestRunner( 3931): 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
07-13 17:19:22.418 I/TestRunner( 3931): 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
07-13 17:19:22.418 I/TestRunner( 3931): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
07-13 17:19:22.419 I/TestRunner( 3931): ----- end exception -----
07-13 17:19:22.420 I/TestRunner( 3931): finished: testHook(sh.calaba.instrumentationbackend.InstrumentationBackend)
```

Tell me if you need more log, then I'll send you a complete log to your email

**Comment by TobiasRoikjer** [comment]
@kristinaste Are you sure you are using the test-server supplied by calabash-android 0.8.0.pre2? You have to run bundle exec calabash-android build <apk> and point to that if you are specifying the test server path yourself. That particular line of code in InstrumentationBackend does not exist

**Comment by kristinaste** [comment]
I've use calabash-android resign myapp.apk before start  with 0.8.0, and then calabash-android run myappp.apk. Test servers are stored in the test_servers folder and it generates every time I execute resign, it is the default location for test servers. I've tried to make it manually: 
```
MacBook-Pro:enigcalabash kristinaste$ calabash-android build /Users/kristinaste/enigcalabash/build/MyApp-debug-test-2.3.4.1.aaa8966.20160704.0956.apk
Done signing the test server. Moved it to test_servers/8aaf580506ee1c3b49d91812fce9aaf4_0.7.3.apk
```

But after I execute ran, it fails anyway.

**Comment by TobiasRoikjer** [comment]
You cannot run a pre-release without bundler.  As read from the name of the built server:  Moved it to test_servers/8aaf580506ee1c3b49d91812fce9aaf4_0.7.3.apk, which is version 0.7.3

**Comment by kristinaste** [comment]
Ook, I've got it :) I've set up a bundler now like this

```ruby
source "https://rubygems.org"
gem 'calabash-cucumber', '0.19.2'
gem 'calabash-android', '0.8.0.pre2'
```

Then I've executed bundle install and run: 

```
bundle exec calabash-android resign /Users/kristinaste/enigcalabash/build/MyApp-debug-test-2.3.4.1.aaa8966.20160704.0956.apk
MacBook-Pro:enigcalabash kristinaste$ bundle exec calabash-android build /Users/kristinaste/enigcalabash/build/MyApp-debug-test-2.3.4.1.aaa8966.20160704.0956.apk
Done signing the test server. Moved it to test_servers/edf6941097fa148f822819d9a5050e3d_0.8.0.pre2.apk
MacBook-Pro:enigcalabash kristinaste$ bundle exec calabash-android run /Users/kristinaste/enigcalabash/build/MyApp-debug-test-2.3.4.1.aaa8966.20160704.0956.apk -p android -p es --tags @SC-2585
Using the android, es and common profiles...
# language: es
@SC-9113 @SC-6123
Característica: Condiciones de usuario

  @SC-2585 @SC-2841 @clear
  Escenario: Condiciones: Al poner solo un tick no deja pasar a la ventana siguiente # features/jira/6_SC-6123.feature:9
 App did not start (RuntimeError)
 ./features/android/support/app_life_cycle_hooks.rb:26:in `Before'
    Dado que estoy en la pagina de condiciones                                       # features/step_definitions/conditions_steps.rb:2
    Cuando acepto las condiciones de tratamiento de datos                            # features/step_definitions/conditions_steps.rb:10
    Entonces no paso a la pagina de login                                            # features/step_definitions/conditions_steps.rb:30

Failing Scenarios:
cucumber -p android -p es -p common features/jira/6_SC-6123.feature:9
```

What I've got in the logs: 

```
--------- beginning of crash
07-13 18:08:22.007 E/AndroidRuntime(15121): FATAL EXCEPTION: main
07-13 18:08:22.007 E/AndroidRuntime(15121): Process: eu.myapp.test, PID: 15121
07-13 18:08:22.007 E/AndroidRuntime(15121): java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{eu.myapp.test.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}: java.lang.RuntimeException: android.content.pm.PackageManager$NameNotFoundException
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4701)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.os.Looper.loop(Looper.java:148)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-13 18:08:22.007 E/AndroidRuntime(15121): Caused by: java.lang.RuntimeException: android.content.pm.PackageManager$NameNotFoundException
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner.onCreate(CalabashInstrumentationTestRunner.java:58)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4698)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	... 8 more
07-13 18:08:22.007 E/AndroidRuntime(15121): Caused by: android.content.pm.PackageManager$NameNotFoundException
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:137)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	at sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner.onCreate(CalabashInstrumentationTestRunner.java:44)
07-13 18:08:22.007 E/AndroidRuntime(15121): 	... 9 more
07-13 18:08:22.038 I/System.out(25743): Failure file: /data/user/0/eu.myapp.test.test/files/calabash_failure.out
07-13 18:08:22.038 I/System.out(25743): Finished file: /data/user/0/eu.myapp.test.test/files/calabash_finished.out
07-13 18:08:22.038 I/System.out(25743): method: report-failure
07-13 18:08:22.040 W/ActivityManager(  780): Error in app eu.myapp.test running instrumentation ComponentInfo{eu.myapp.test.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}:
07-13 18:08:22.040 W/ActivityManager(  780):   android.content.pm.PackageManager$NameNotFoundException
07-13 18:08:22.040 W/ActivityManager(  780):   android.content.pm.PackageManager$NameNotFoundException: android.content.pm.PackageManager$NameNotFoundException
07-13 18:08:22.040 I/ActivityManager(  780): Force stopping eu.myapp.test appid=10251 user=0: finished inst
07-13 18:08:22.041 I/ActivityManager(  780): Killing 15121:eu.myapp.test/u0a251 (adj 0): stop eu.myapp.test
```

Did I miss something?

**Comment by TobiasRoikjer** [comment]
@kristinaste It appears the applications are not being installed. Reading your code
```ruby
INSTALLATION_STATE = {
    :installed => true
}

Before do |scenario|
  scenario_tags = scenario.source_tag_names
  if !INSTALLATION_STATE[:installed]
      uninstall_apps
      install_app(ENV['TEST_APP_PATH'])
      install_app(ENV['APP_PATH'])
      INSTALLATION_STATE[:installed] = true
  end
```

The applications would never be reinstalled. This includes the new test-server

**Comment by kristinaste** [comment]
INSTALLATION_STATE was assigned to true to avoid reinstalling the app every test execution.  I have all the installation routine in the setup part like : 
' calabash-android console myapp.apk <<< "reinstall_apps"' and it worked in 0.7.3

After I changed the :installed => false, it gives no error now and the executions starts. Guess I should find another way to avoid reinstalling the app every launch. 

Thank you.
