### ISSUE TITLE
calabash-android run always has error "android.util.AndroidException: INSTRUMENTATION_FAILED: 

### ISSUE THREAD

**Issue by angeliaw** [calabash/calabash-android#767]
calabash-android run <apk> always has this error, I tried calabash-android console <apk> also has this error, but in console, if i 'reinstall_apps' then 'start_test_server_in_background' could be successful. 

i was totally confused, i checked support files which were generated by 'calabash-android gen'

```
android.util.AndroidException: INSTRUMENTATION_FAILED: xxxx/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
	at com.android.commands.am.Am.runInstrument(Am.java:1121)
	at com.android.commands.am.Am.onRun(Am.java:374)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
	at com.android.commands.am.Am.main(Am.java:103)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:257)

```

**Comment by TobiasRoikjer** [comment]
Are you sure the app/test server are both installed? What version are you using?
Does ADB logcat say anything?

**Comment by mfeltmann** [comment]
Same here followed by [App did not start (RuntimeError)](https://github.com/calabash/calabash-android/issues/731)
Mac OS X 10.11.6 had an awful lot of permission issues when it comes to ruby. Maybe source of this issues?
