### ISSUE TITLE
RunTime Error on using touch method - calabash-android version 0.8.0

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#768]
Hi,

I am getting an error saying `map webview css:'#xxxxx', query failed because: java.util.concurrent.TimeoutException: Timeout while waiting for value(RuntimeError). `

fails for this command - touch("webview css:'"+element+"'")

Error Logs:
`08-23 23:11:36.614 23880 31395 W System.err: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timeout while waiting for value
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:67)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.evaluation.UIQueryEvaluationStep.step(UIQueryEvaluationStep.java:40)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.evaluation.QueryEvaluator.evaluateQueryForPath(QueryEvaluator.java:19)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:52)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:16)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:68)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:308)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
08-23 23:11:36.614 23880 31395 W System.err: 	at java.lang.Thread.run(Thread.java:841)
08-23 23:11:36.614 23880 31395 W System.err: Caused by: java.util.concurrent.TimeoutException: Timeout while waiting for value
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.actions.webview.CalabashChromeClient$WebFuture.get(CalabashChromeClient.java:456)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$1.call(UIQueryASTWith.java:200)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith$1.call(UIQueryASTWith.java:197)
08-23 23:11:36.614 23880 31395 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTWith.evaluateWithViews(UIQueryASTWith.java:64)`

System details
- Calabash version: 0.8.0
- OS: Ubuntu 14.04 trusty
- Ruby: ruby 2.0.0p384 (2014-01-12) [x86_64-linux-gnu]
- Java: java 7 openjdk
- Device: Samsung Galaxy Grand Prime Duos (OS 4.4.4)

**Comment by TobiasRoikjer** [comment]
What is the selector?  `touch("webview css:'"+element+"'")` is invalid

**Comment by DineshKumar7** [comment]
The exact query I use is - touch("webview css:'#submitOrder'")

Element details - Its a button identifier: "id" => "submitOrder",

**Comment by TobiasRoikjer** [comment]
Is the error consistent?

**Comment by DineshKumar7** [comment]
Hai, 
   Yes the error is consistent on the above mentioned device - (which is Samsung Galaxy Grand Prime Duos (OS 4.4.4) ). However on other devices, the reproduction rate is too low - like (1/10).
