### ISSUE TITLE
Runtime Error: query failed because: java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#786]
Hai, 
    I am getting the bellow error after upgrading to calabash-android v0.8.4. Please check and let me know how can I overcome this issue. Thanks

`map * id:'splash_progress', query failed because: java.util.concurrent.TimeoutException` 

Query used - wait_for(:timeout => 60) { element_does_not_exist("* id:'splash_progress'")}

logs:
`W/System.err(22976): java.lang.RuntimeException: java.util.concurrent.TimeoutException
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTClassName.evaluateWithViews(UIQueryASTClassName.java:137)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.ast.evaluation.UIQueryEvaluationStep.step(UIQueryEvaluationStep.java:40)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.ast.evaluation.QueryEvaluator.evaluateQueryForPath(QueryEvaluator.java:19)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:51)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:16)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:56)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:575)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
W/System.err(22976): 	at java.lang.Thread.run(Thread.java:841)
W/System.err(22976): Caused by: java.util.concurrent.TimeoutException
W/System.err(22976): 	at java.util.concurrent.FutureTask.get(FutureTask.java:173)
W/System.err(22976): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTClassName.evaluateWithViews(UIQueryASTClassName.java:129)
W/System.err(22976): 	... 8 more`

System details
Ubuntu 16.04
ruby 2.3.1p112
Java - openjdk version "1.8.0_111"
calabash-android v0.8.4

Device details
Samsung s3 (OS 4.3).

**Comment by TobiasRoikjer** [comment]
Likely your UI thread is frozen.

**Comment by rohsin02** [comment]
I am getting the same error:
map * id:'progress', query failed because: java.util.concurrent.TimeoutException

java.lang.RuntimeException: java.util.concurrent.TimeoutException
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTClassName.evaluateWithViews(UIQueryASTClassName.java:133)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.ast.evaluation.UIQueryEvaluationStep.step(UIQueryEvaluationStep.java:40)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.ast.evaluation.QueryEvaluator.evaluateQueryForPath(QueryEvaluator.java:19)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryForPath(UIQueryEvaluator.java:52)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryEvaluator.evaluateQueryWithOptions(UIQueryEvaluator.java:16)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.Query.executeQuery(Query.java:68)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:308)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:478)
02-16 13:23:14.916 W/System.err( 9463): 	at java.lang.Thread.run(Thread.java:818)
02-16 13:23:14.916 W/System.err( 9463): Caused by: java.util.concurrent.TimeoutException
02-16 13:23:14.916 W/System.err( 9463): 	at java.util.concurrent.FutureTask.get(FutureTask.java:176)
02-16 13:23:14.916 W/System.err( 9463): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryASTClassName.evaluateWithViews(UIQueryASTClassName.java:125)
02-16 13:23:14.916 W/System.err( 9463): 	... 8 more

calabash-android v0.7.3
ruby 2.3.1

Please check and let me know how can i fix this issue?

**Comment by PriyalSayonetech** [comment]
@rohsin02 @TobiasRoikjer @DineshKumar7  did you guys get it?

**Comment by srinukodi** [comment]
Bumping up this to see if anyone has come across this situation along with a solution.

**Comment by owenniblock** [comment]
I've seen this issue a few times over the last week but struggling to replicate locally. My theory is that it's Calabash trying to access a View after the GC has cleared it up.

A workaround seems to be adding a wait in before you start querying the app (so that the UI can stabilise). I would advise trying that if you're seeing this issue.
