### ISSUE TITLE
Failure [INSTALL_FAILED_INVALID_APK]

### ISSUE THREAD

**Issue by redjames** [calabash/calabash-android#791]
When I install an APK through adb, it installed without problems. However when I sign the app with `calabash-android resign` I get this error:

```
[100%] /data/local/tmp/xxxx.apk
       	pkg: /data/local/tmp/xxxx.apk
Failure [INSTALL_FAILED_INVALID_APK]
```

And if I do it from calabash-android console:

```
irb(main):002:0> reinstall_apps
RuntimeError: com.xxx.android did not get installed. Reason: 'Failure [INSTALL_FAILED_INVALID_APK]'. Aborting!
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-android-0.8.2/lib/calabash-android/operations.rb:351:in `install_app'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-android-0.8.2/lib/calabash-android/operations.rb:327:in `reinstall_apps'
       	from /Users/james/.rvm/gems/ruby-2.3.0/gems/calabash-android-0.8.2/lib/calabash-android/operations.rb:106:in `reinstall_apps'
       	from (irb):2
       	from /Users/james/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

And when install the apk directly in the device, the pop-up messages shows:
_It looks like the package is damaged_

Is this because some privileges grants that I need?

Thanks in advance.

**Comment by TobiasRoikjer** [comment]
We don't really have enough information to debug this. What version are you using, what are the logs when running everything (including the resign) using DEBUG=1
