### ISSUE TITLE
Getting run time error after upgrading to calabash-android v0.8.4

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#792]
Hai, 
       I am getting the below error after upgrading the calabash-android version to 0.8.4. Where the app exception is handled.  

`map * id:'progress_container', query failed because: storage == nul
       (RuntimeError)`

`D/Ad4PushTracker(18145): Started Activity -> pt.rocket.view.activities.SplashScreenActivity
D/pushio  (18145): PPM key: SHOP_COUNTRY, value: null
D/pushio  (18145): PPM mPreferenceTempHolder.containsKey
D/pushio  (18145): PPM isValidKey
W/System.err(18145): com.pushio.manager.exception.ValidationException: value type different from the type declared.
W/System.err(18145): 	at com.pushio.manager.PushIOPreferencesManager.setPreference(PushIOPreferencesManager.java:131)
W/System.err(18145): 	at com.pushio.manager.PushIOManager.setPref(PushIOManager.java:859)
W/System.err(18145): 	at com.pushio.manager.PushIOManager.setPreference(PushIOManager.java:816)
W/System.err(18145): 	at pt.rocket.framework.utils.PushIOTracker.trackStartActivity(PushIOTracker.java:622)
W/System.err(18145): 	at pt.rocket.utils.TrackerDelegator.startActivity(TrackerDelegator.java:459)
W/System.err(18145): 	at pt.rocket.view.activities.BaseActivity.onResume(BaseActivity.java:186)
W/System.err(18145): 	at pt.rocket.view.activities.SplashScreenActivity.onResume(SplashScreenActivity.java:169)
W/System.err(18145): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1209)
W/System.err(18145): 	at sh.calaba.instrumentationbackend.CalabashInstrumentation.callActivityOnResume(CalabashInstrumentation.java:86)
W/System.err(18145): 	at android.app.Activity.performResume(Activity.java:5450)
W/System.err(18145): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2909)
W/System.err(18145): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2948)
W/System.err(18145): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2354)
W/System.err(18145): 	at android.app.ActivityThread.access$700(ActivityThread.java:159)
W/System.err(18145): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
W/System.err(18145): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(18145): 	at android.os.Looper.loop(Looper.java:137)
W/System.err(18145): 	at android.app.ActivityThread.main(ActivityThread.java:5419)
W/System.err(18145): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(18145): 	at java.lang.reflect.Method.invoke(Method.java:525)
W/System.err(18145): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
W/System.err(18145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
W/System.err(18145): 	at dalvik.system.NativeStart.main(Native Method)
`

System details
Ubuntu 14.04
ruby 2.3.1p112
Java - openjdk version "1.7.0_79"
calabash-android v 0.8.4

Device details
Samsung s3 (OS 4.3).

Note: This issue doesn't happen on v 0.8.2

**Comment by TobiasRoikjer** [comment]
Can you email me the apk?

**Comment by DineshKumar7** [comment]
@TobiasRoikjer I have emailed you the apk file.

**Comment by TobiasRoikjer** [comment]
@DineshKumar7 I did not receive anything over email

**Comment by DineshKumar7** [comment]
@TobiasRoikjer - I have sent the file to this mail ID - `tobias.roikjer@xamarin.com`. Please let me know if your email service is different. Thanks

**Comment by TobiasRoikjer** [comment]
@DineshKumar7 That is the correct email, but I did not receive anything, perhaps it is being filtered? Could you please try sending an email without the APK to see if it goes through? Thank you very much for helping fixing this issue.
