### ISSUE TITLE
Getting run time (Could not detect visibility of sh.calaba.instrumentationbackend.query.ui.UIObjectView@ba1fcdc) error after upgrading to calabash-android v0.8.4

### ISSUE THREAD

**Issue by DineshKumar7** [calabash/calabash-android#795]
Hai,
I am getting the below error after upgrading the calabash-android version to 0.8.4. 

query used - wait_for(:timeout => 120) {element_does_not_exist("* id:'item_text'")}

Error:-
`map * id:'item_text', query failed because: Could not detect visibility of sh.calaba.instrumentationbackend.query.ui.UIObjectView@ba1fcdc`

Log:-
`11-30 20:06:19.383 30782 31400 W System.err: java.lang.RuntimeException: Could not detect visibility of sh.calaba.instrumentationbackend.query.ui.UIObjectView@ba1fcdc
11-30 20:06:19.383 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isVisible(UIQueryUtils.java:213)
11-30 20:06:19.383 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ViewMapper.extractDataFromView(ViewMapper.java:33)
11-30 20:06:19.383 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ViewMapper.mapResult(ViewMapper.java:107)
11-30 20:06:19.383 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ViewMapper.mapList(ViewMapper.java:134)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.QueryResult.asMappedList(QueryResult.java:15)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.FranklyResult.asMap(FranklyResult.java:59)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.FranklyResult.asJson(FranklyResult.java:51)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:578)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
11-30 20:06:19.384 30782 31400 W System.err: 	at java.lang.Thread.run(Thread.java:761)
11-30 20:06:19.384 30782 31400 W System.err: Caused by: java.lang.NullPointerException: null receiver
11-30 20:06:19.384 30782 31400 W System.err: 	at java.lang.reflect.Field.get(Native Method)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View$AttachInfo.initializeFromAndroidAttachInfo(ViewWrapper.java:260)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:181)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-30 20:06:19.384 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.utils.ViewWrapper.<init>(ViewWrapper.java:107)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.getViewLocationOnScreen(UIQueryUtils.java:261)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ViewMapper.getRectForView(ViewMapper.java:57)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isViewSufficientlyShown(UIQueryUtils.java:628)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isViewSufficientlyShown(UIQueryUtils.java:233)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryVisibilityMatcher.matchForUIObject(UIQueryVisibilityMatcher.java:26)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryVisibilityMatcher.matchForUIObject(UIQueryVisibilityMatcher.java:13)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryMatcher.call(UIQueryMatcher.java:23)
11-30 20:06:19.385 30782 31400 W System.err: 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isVisible(UIQueryUtils.java:211)
11-30 20:06:19.385 30782 31400 W System.err: 	... 9 more`

System details
Ubuntu 12.04
ruby 2.0.0p353
Java - openjdk version "1.7.0_51"
calabash-android v 0.8.4

Device details
Nexus 6 (7.0)

Note: This issue doesn't happen on v 0.8.2

**Comment by TobiasRoikjer** [comment]
@DineshKumar7 Thank you, could you please post the full device OS? Does this happen 100% of the time? Are you sure this did not happen in 0.8.2?

**Comment by kevgatch** [comment]
I'm using v 0.8.2 and I encounter this same error sometimes.

System details
ruby - 2.1.7p400
Java - 1.8.0_45
calabash-android - 0.8.2

Device details
ASUS_T00J (android 4.4.2)

**Comment by kapilag** [comment]
I am also getting the same error sometimes, it's not consistent but usually pops up on webview pages.

**Error:**
map * id:'progress', query failed because: Could not detect visibility of sh.calaba.instrumentationbackend.query.ui.UIObjectView@32b1ab0

**ADB logs:**

11-22 12:43:57.871 W/System.err(12478): java.lang.RuntimeException: Could not detect visibility of sh.calaba.instrumentationbackend.query.ui.UIObjectView@32b1ab0
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isVisible(UIQueryUtils.java:213)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ViewMapper.extractDataFromView(ViewMapper.java:33)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ViewMapper.mapResult(ViewMapper.java:107)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ViewMapper.mapList(ViewMapper.java:134)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.QueryResult.asMappedList(QueryResult.java:15)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.FranklyResult.asMap(FranklyResult.java:59)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.FranklyResult.asJson(FranklyResult.java:51)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.actions.HttpServer.serve(HttpServer.java:578)
11-22 12:43:57.871 W/System.err(12478): 	at sh.calaba.instrumentationbackend.actions.NanoHTTPD$HTTPSession.run(NanoHTTPD.java:487)
11-22 12:43:57.872 W/System.err(12478): 	at java.lang.Thread.run(Thread.java:761)
11-22 12:43:57.872 W/System.err(12478): Caused by: java.lang.NullPointerException: null receiver
11-22 12:43:57.872 W/System.err(12478): 	at java.lang.reflect.Field.get(Native Method)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View$AttachInfo.initializeFromAndroidAttachInfo(ViewWrapper.java:260)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:181)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.utils.ViewWrapper$View.initializeFromAndroidView(ViewWrapper.java:167)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.utils.ViewWrapper.<init>(ViewWrapper.java:107)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.getViewLocationOnScreen(UIQueryUtils.java:261)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ViewMapper.getRectForView(ViewMapper.java:57)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isViewSufficientlyShown(UIQueryUtils.java:629)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isViewSufficientlyShown(UIQueryUtils.java:631)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isViewSufficientlyShown(UIQueryUtils.java:631)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isViewSufficientlyShown(UIQueryUtils.java:233)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryVisibilityMatcher.matchForUIObject(UIQueryVisibilityMatcher.java:26)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryVisibilityMatcher.matchForUIObject(UIQueryVisibilityMatcher.java:13)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryMatcher.call(UIQueryMatcher.java:23)
11-22 12:43:57.872 W/System.err(12478): 	at sh.calaba.instrumentationbackend.query.ast.UIQueryUtils.isVisible(UIQueryUtils.java:211)
11-22 12:43:57.872 W/System.err(12478): 	... 9 more

**Calabash-android version**  : 0.9.0
emulator : Nexus 5, API25
