### ISSUE TITLE
[Windows] No signature files found in META-INF. Cannot proceed.

### ISSUE THREAD

**Issue by d-konovalov** [calabash/calabash-android#802]
When I run this command: 
```calabash-android build BuildName.apk```
on mac all works as expected
but if I try to do it on windows I get next error:

```C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk': No signature files found in META-INF. Cannot proceed. (RuntimeError)
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:170:in `chdir'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:170:in `block in fingerprint_from_apk'
	from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:169:in `fingerprint_from_apk'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:2:in `calabash_build'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android:72:in `<top (required)>'
	from C:/Ruby22-x64/bin/calabash-android:23:in `load'
	from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'```

Please help me to find what I do wrong 
Best regards

**Comment by TobiasRoikjer** [comment]
The application is not signed, you need to run the `resign` command. e.g. `calabash-android resign <apk>`. (I also heavily recommend you use bundler to manage you gem versions)

**Comment by d-konovalov** [comment]
Thank you for super fast response
once i've tried to execute command you just provided I get this error message:


```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:60:in `sign_apk': Could not sign app: C:/Users/Test/AppData/Local/Temp/d20170117-6456-w7dzrc/unsigned.apk (RuntimeError)
 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:164:in `sign_apk'
 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:119:in `block in resign_apk'
 	from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:113:in `resign_apk'
 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android:133:in `<top (required)>'
 	from C:/Ruby22-x64/bin/calabash-android:23:in `load'
 	from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'
 2017-01-17 13:25:24 - Resign apk
 DEBUG: Setting Android SDK location to $ANDROID_HOME
 DEBUG: Android SDK location set to 'C:\Users\Test\AppData\Local\Android\Sdk'
 DEBUG: Set aapt path to 'C:\Users\Test\AppData\Local\Android\Sdk/build-tools/25.0.2/aapt.exe'
 DEBUG: Set zipalign path to 'C:\Users\Test\AppData\Local\Android\Sdk/build-tools/25.0.2/zipalign.exe'
 DEBUG: Set adb path to 'C:\Users\Test\AppData\Local\Android\Sdk/platform-tools/adb.exe'
 DEBUG: Set android jar path to 'C:\Users\Test\AppData\Local\Android\Sdk/platforms/android-25/android.jar'
 DEBUG: Setting Java SDK location from HKEY_LOCAL_MACHINE SOFTWARE\JavaSoft\Java Development Kit\1.8
 DEBUG: Java SDK location set to 'C:\Program Files\Java\jdk1.8.0_111'
 DEBUG: Found java on PATH
 DEBUG: Set java path to '\Program Files\Java\jre1.8.0_111\bin/java.exe'
 DEBUG: Found keytool on PATH
 DEBUG: Set keytool path to '\Program Files\Java\jre1.8.0_111\bin/keytool.exe'
 DEBUG: Found jarsigner on PATH
 DEBUG: Set jarsigner path to '\Program Files\Java\jdk1.8.0_111\bin/jarsigner.exe'
```

**Comment by TobiasRoikjer** [comment]
@d-konovalov What is the full ouput (including the command you have executed)?

**Comment by d-konovalov** [comment]
@TobiasRoikjer 


```
[split_2] C:\Jenkins\workspace\TemplateYouseeAndroidOutage@4>rake feature_run[01f57440,default,outage,android,yousee,45640,feature_playlists_actions] 
[split_2] cp ./keystores/yousee_calabash_settings ./.calabash_settings
[split_2] bundle exec calabash-android resign Music.Droid.YouSee_3.5.0.380.apk
[split_2] ERROR: failed opening 'C:/Users/Test/AppData/Local/Temp/d20170117-6456-w7dzrc/unsigned.apk' as Zip file
[split_2] C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:60:in `sign_apk': Could not sign app: C:/Users/Test/AppData/Local/Temp/d20170117-6456-w7dzrc/unsigned.apk (RuntimeError)
[split_2] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:164:in `sign_apk'
[split_2] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:119:in `block in resign_apk'
[split_2] 	from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
[split_2] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:113:in `resign_apk'
[split_2] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android:133:in `<top (required)>'
[split_2] 	from C:/Ruby22-x64/bin/calabash-android:23:in `load'
[split_2] 	from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'
[split_2] 2017-01-17 13:25:24 - Resign apk
[split_2] DEBUG: Setting Android SDK location to $ANDROID_HOME
[split_2] DEBUG: Android SDK location set to 'C:\Users\Test\AppData\Local\Android\Sdk'
[split_2] DEBUG: Set aapt path to 'C:\Users\Test\AppData\Local\Android\Sdk/build-tools/25.0.2/aapt.exe'
[split_2] DEBUG: Set zipalign path to 'C:\Users\Test\AppData\Local\Android\Sdk/build-tools/25.0.2/zipalign.exe'
[split_2] DEBUG: Set adb path to 'C:\Users\Test\AppData\Local\Android\Sdk/platform-tools/adb.exe'
[split_2] DEBUG: Set android jar path to 'C:\Users\Test\AppData\Local\Android\Sdk/platforms/android-25/android.jar'
[split_2] DEBUG: Setting Java SDK location from HKEY_LOCAL_MACHINE SOFTWARE\JavaSoft\Java Development Kit\1.8
[split_2] DEBUG: Java SDK location set to 'C:\Program Files\Java\jdk1.8.0_111'
[split_2] DEBUG: Found java on PATH
[split_2] DEBUG: Set java path to '\Program Files\Java\jre1.8.0_111\bin/java.exe'
[split_2] DEBUG: Found keytool on PATH
[split_2] DEBUG: Set keytool path to '\Program Files\Java\jre1.8.0_111\bin/keytool.exe'
[split_2] DEBUG: Found jarsigner on PATH
[split_2] DEBUG: Set jarsigner path to '\Program Files\Java\jdk1.8.0_111\bin/jarsigner.exe'
[split_2] 2017-01-17 13:25:25 - App wasn't signed. Will not try to unsign it.
[split_2] 2017-01-17 13:25:25 - Keystore location specified in .calabash_settings.
[split_2] 2017-01-17 13:25:25 - Reading keystore data from keystore file 'C:/Jenkins/workspace/TemplateYouseeAndroidOutage@4/keystores/yousee.keystore'
[split_2] 2017-01-17 13:25:25 - "\Program Files\Java\jre1.8.0_111\bin/keytool.exe" -list -v -alias juke -keystore C:/Jenkins/workspace/TemplateYouseeAndroidOutage@4/keystores/yousee.keystore -storepass JukeNukeEm "-J"-Dfile.encoding=utf-8"" "-J"-Duser.language=en-US""
[split_2] 2017-01-17 13:25:27 - Key store data:
[split_2] 2017-01-17 13:25:27 - Alias name: juke
[split_2] Creation date: Aug 3, 2011
[split_2] Entry type: PrivateKeyEntry
[split_2] Certificate chain length: 1
[split_2] Certificate[1]:
[split_2] Owner: CN=247 Entertainment, L=Copenhagen, C=DK
[split_2] Issuer: CN=247 Entertainment, L=Copenhagen, C=DK
[split_2] Serial number: 4e392aa9
[split_2] Valid from: Wed Aug 03 14:02:01 EEST 2011 until: Sun Jul 27 14:02:01 EEST 2036
[split_2] Certificate fingerprints:
[split_2] 	 MD5:  6C:64:4D:17:AF:EA:96:E8:36:CF:7D:4C:60:98:8C:C1
[split_2] 	 SHA1: 2C:94:FA:F6:B4:D9:C3:FF:CF:3C:C3:D8:E7:87:13:92:7E:F5:3D:17
[split_2] 	 SHA256: 9B:60:58:F6:D8:7F:96:65:46:FE:B6:AE:70:29:07:3D:98:55:59:65:BF:DF:39:73:57:57:C7:11:32:CE:B0:14
[split_2] 	 Signature algorithm name: SHA1withRSA
[split_2] 	 Version: 3
[split_2] 2017-01-17 13:25:27 - Fingerprint: B4:D9:C3:FF:CF:3C:C3:D8:E7:87:13:92:7E:F5:3D:17
[split_2] 2017-01-17 13:25:27 - Signature algorithm name: SHA1withRSA
[split_2] 2017-01-17 13:25:27 - Signing using the signature algorithm: 'SHA1withRSA'
[split_2] 2017-01-17 13:25:27 - Signing using the digest algorithm: 'SHA1'
[split_2] 2017-01-17 13:25:27 - "\Program Files\Java\jdk1.8.0_111\bin/jarsigner.exe" -sigfile CERT -sigalg SHA1withRSA -digestalg SHA1 -signedjar C:/Users/Test/AppData/Local/Temp/d20170117-6456-w7dzrc/unaligned.apk -storepass JukeNukeEm -keystore C:/Jenkins/workspace/TemplateYouseeAndroidOutage@4/keystores/yousee.keystore C:/Users/Test/AppData/Local/Temp/d20170117-6456-w7dzrc/unsigned.apk juke
```

Thank you

**Comment by d-konovalov** [comment]
The next line is attempt to build it ```calabash-android build <apk-file>```

**Comment by d-konovalov** [comment]
hm
did you delete the output I've posted 15 mins ago?

**Comment by TobiasRoikjer** [comment]
@d-konovalov I did, I just wanted to make sure the output did not contain any sensitive information.

**Comment by d-konovalov** [comment]
Thank you

**Comment by TobiasRoikjer** [comment]
@d-konovalov Run using `DEBUG=1 bundle exec calabash-android resign <apk> -v`

Look for the line below Signing using the digest algorithm: <xxxx>.
Try executing that command on its own

**Comment by d-konovalov** [comment]
@TobiasRoikjer 
It seems that resign worked without errors

```
[split_1] DEBUG=1 bundle exec calabash-android resign Music.Droid.YouSee_3.5.0.380.apk -v
[split_1] cp ./keystores/yousee_calabash_settings ./.calabash_settings
[split_1] bundle exec calabash-android build Music.Droid.YouSee_3.5.0.380.apk
[split_1] C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk': No signature files found in META-INF. Cannot proceed. (RuntimeError)
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:170:in `chdir'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:170:in `block in fingerprint_from_apk'
[split_1] 	from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:169:in `fingerprint_from_apk'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:2:in `calabash_build'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android:72:in `<top (required)>'
[split_1] 	from C:/Ruby22-x64/bin/calabash-android:23:in `load'
[split_1] 	from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'
[split_1] 2017-01-17 16:25:51 - Signature files:
```
But as you can see the initial error message is still available

Thanks

**Comment by TobiasRoikjer** [comment]
You have to build the the same .calabash_settings as the ones you use to resign it.

**Comment by d-konovalov** [comment]
hm
you mean I should run resign command after I copy .calabash_settings file?

**Comment by TobiasRoikjer** [comment]
Yes. Calabash *has* to have a server (created using build) signed used the same credentials as the app under test (resigned using resign)

**Comment by d-konovalov** [comment]
I've changed order of these actions but the output is the same (


```
[split_1] cp ./keystores/yousee_calabash_settings ./.calabash_settings
[split_1] DEBUG=1 bundle exec calabash-android resign Music.Droid.YouSee_3.5.0.380.apk -v
[split_1] bundle exec calabash-android build Music.Droid.YouSee_3.5.0.380.apk
[split_1] C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk': No signature files found in META-INF. Cannot proceed. (RuntimeError)
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:170:in `chdir'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:170:in `block in fingerprint_from_apk'
[split_1] 	from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:169:in `fingerprint_from_apk'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:2:in `calabash_build'
[split_1] 	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/bin/calabash-android:72:in `<top (required)>'
[split_1] 	from C:/Ruby22-x64/bin/calabash-android:23:in `load'
[split_1] 	from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'
[split_1] 2017-01-17 16:54:28 - Signature files:
```

**Comment by TobiasRoikjer** [comment]
@d-konovalov Unzip the apk after running `resign`, and look into the directory named META-INF, what do you see?

**Comment by d-konovalov** [comment]
I can see MANIFEST.MF, CERT.SF and CERT.RSA files
i just did resign locally and saw valid output without any errors
the errors i posted here copied from remote run (via jenkins) from the same machine 
after resigning locally ```calabash-android build <apk>``` worked without any errors :(

**Comment by TobiasRoikjer** [comment]
To confirm, on the CI machine, you resigned the app, and on the CI machine, you unzipped the app, and saw those files in the META-INF directory?

**Comment by d-konovalov** [comment]
Yep
I did it manually on that machine and succeeded
but when i try to resign it remotely with script I see the error again (after resign step)

**Comment by TobiasRoikjer** [comment]
And you are doing it from the same directory and user as the CI script is running as?

**Comment by d-konovalov** [comment]
The directory is the same but I'm not sure about the user

**Comment by d-konovalov** [comment]
This one is still happens when triggered by CI 

```C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:60:in `sign_apk': Could not sign app: C:/Users/Test/AppData/Local/Temp/d20170117-7352-1c81xzp/unsigned.apk (RuntimeError)```

**Comment by TobiasRoikjer** [comment]
To confirm, that happens when you execute `build`, and not  `resign`?

**Comment by d-konovalov** [comment]
That's right
When 'resign'

When 'build' I see the error from the first message

**Comment by andreroggeri** [comment]
Probably you're using the JDK 151 or 152.

These versions of JDK changed the way that keytool works.

The quick fix for this is downgrading the JDK to 144 (previous version). And your error should be fixed

**Comment by ruttuk** [comment]
Hello, I am having the exact same issue. I've tried downgrading to JDK 144 and still I see the following:

```
bundle exec calabash-android run kingmaker.apk
WARNING: skipped META-INF/CERT.RSA as unsafe
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk': No signature files found in META-INF. Cannot proceed. (RuntimeError)
```

**Comment by KGMSathish** [comment]
Guys i'm also facing same issue, after resigning the apk(resigning will be success) 

`C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk': No signatu
re files found in META-INF. Cannot proceed. (RuntimeError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:170:in `chdir'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:170:in `block in fingerprint_from_apk'
        from C:/Ruby23-x64/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:169:in `fingerprint_from_apk'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.6/bin/calabash-android-build.rb:2:in `calabash_build'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.6/bin/calabash-android:72:in `<top (required)>'
        from C:/Ruby23-x64/bin/calabash-android:22:in `load'
        from C:/Ruby23-x64/bin/calabash-android:22:in `<main>'`

**Comment by ruttuk** [comment]
@KGMSathish try updating the version of calabash-android to 0.9.5 and rubyzip to 1.2.1.

**Comment by SathishKadavanna** [comment]
@ruttuk Thanks a tonne, i removed ruby fully & installed Ruby 2.5.1, RubyZip 1.2.1, Calabash-Android 0.9.5
With this its working fine. Thanks @ruttuk :100:

**Comment by shahbaz-qaiser-10p** [comment]
@TobiasRoikjer facing the same issue can you help me with it?

**Comment by GiuseppeGiacoppo** [comment]
@shahbaz-qaiser-10p 
I had problems even with ruttuk's solution. 
On Windows I solved installing Ruby+Devkit instead of Ruby alone. Then created a Gemfile specifying RubyZip 1.2.1 and calabash-android 0.9.5 and it worked.

**Comment by JoeSSS** [comment]
hey does it still happen with 0.9.22 version of the gem?
