### ISSUE TITLE
Unable to get screenshot from calabash android 0.9.0

### ISSUE THREAD

**Issue by liaogz82** [calabash/calabash-android#816]
I am unable to take screenshot of my simulator using calabash-android 0.9.0. Below are the error logs
```
2017-04-04 10:50:26 - "/opt/android/platform-tools/adb" -s emulator-5784 shell am instrument -e main_activity null -e test_server_port 7102 -e class sh.calaba.instrumentationbackend.InstrumentationBackend sg.com.singaporepower.spservices.dev.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner
  Background:                # features/features/01_tnc.feature:3
  App did not start (RuntimeError)
  ./features/features/support/app_life_cycle_hooks.rb:5:in `Before'
    Given the app is running # features/features/01_tnc.feature:4

  Scenario: As I launch the app for the first time      # features/features/01_tnc.feature:6
      #Current screen: FirstRunActivity
    Then I long swipe right                             # features/features/step_definitions/calabash_steps.rb:3
    Then I long swipe right                             # features/features/step_definitions/calabash_steps.rb:3
    Then I long swipe right                             # features/features/step_definitions/calabash_steps.rb:3
    Then I long swipe right                             # features/features/step_definitions/calabash_steps.rb:3
    Then I press view with id "acceptTnCBtn"            # calabash-android-0.9.0/lib/calabash-android/steps/press_button_steps.rb:13
    Then I wait for the "MenuActivity" screen to appear # calabash-android-0.9.0/lib/calabash-android/steps/progress_steps.rb:51
    Then I wait                                         # calabash-android-0.9.0/lib/calabash-android/steps/progress_steps.rb:5
2017-04-04 10:50:41 - java -jar "/var/lib/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/lib/screenshotTaker.jar" emulator-5784 "/tmp/foo/screenshot_0.png"
Could not take screenshot
java.io.IOException: EOF
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:643)
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:616)
	at com.android.ddmlib.AdbHelper.getFrameBuffer(AdbHelper.java:296)
	at com.android.ddmlib.CalabashAdbHelper.getFrameBuffer(Unknown Source)
	at com.android.ddmlib.CalabashDevice.getScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.takeScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.main(Unknown Source)
```

Any advise?

**Comment by TobiasRoikjer** [comment]
Are you sure the device is properly started and connected over ADB? Calabash fails to launch the application as well.

**Comment by liaogz82** [comment]
sorry wrong logs. this is the correct one

```
Success
  Background:                # features/02_login/login.feature:4
    Given the app is running # features/android/step_definitions/common_actions.rb:8
Could not take screenshot
java.io.IOException: EOF
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:643)
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:616)
	at com.android.ddmlib.AdbHelper.getFrameBuffer(AdbHelper.java:296)
	at com.android.ddmlib.CalabashAdbHelper.getFrameBuffer(Unknown Source)
	at com.android.ddmlib.CalabashDevice.getScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.takeScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.main(Unknown Source)

```

**Comment by ea2809** [comment]
In jenkins too:

```Success
Success
Could not take screenshot
java.io.IOException: EOF
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:643)
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:616)
	at com.android.ddmlib.AdbHelper.getFrameBuffer(AdbHelper.java:296)
	at com.android.ddmlib.CalabashAdbHelper.getFrameBuffer(Unknown Source)
	at com.android.ddmlib.CalabashDevice.getScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.takeScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.main(Unknown Source)
Could not take screenshot
java.io.IOException: EOF
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:643)
	at com.android.ddmlib.AdbHelper.read(AdbHelper.java:616)
	at com.android.ddmlib.AdbHelper.getFrameBuffer(AdbHelper.java:296)
	at com.android.ddmlib.CalabashAdbHelper.getFrameBuffer(Unknown Source)
	at com.android.ddmlib.CalabashDevice.getScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.takeScreenshot(Unknown Source)
	at sh.calaba.screenshot.ScreenshotTaker.main(Unknown Source)```
