### ISSUE TITLE
invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by gunesmes** [calabash/calabash-android#820]
We have updated Macos to Sierra then got the following error. It works ok under El Capitan. Help me how could I solve the problem:

```
canberksevdeger:testautomation canberksevdeger$ cucumber -p android prebuilt/Moda_v2.3.13_com.apk features/header.feature  -v
Code:
  * features/support/env.rb
  * features/android/support/app_life_cycle_hooks.rb
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to '/Users/canberksevdeger/Library/Android/sdk'
DEBUG: Set aapt path to '/Users/canberksevdeger/Library/Android/sdk/build-tools/25.0.2/aapt'
DEBUG: Set zipalign path to '/Users/canberksevdeger/Library/Android/sdk/build-tools/25.0.2/zipalign'
DEBUG: Set adb path to '/Users/canberksevdeger/Library/Android/sdk/platform-tools/adb'
DEBUG: Set android jar path to '/Users/canberksevdeger/Library/Android/sdk/platforms/android-25/android.jar'
DEBUG: Setting Java SDK location to $JAVA_HOME
DEBUG: Java SDK location set to '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home'
DEBUG: Found java on PATH
DEBUG: Set java path to '/usr/bin/java'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '/usr/bin/keytool'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '/usr/bin/jarsigner'
  * features/android/support/ids.rb
  * features/android/support/messages.rb
  * features/support/credentials.rb
  * features/support/functions.rb
  * features/support/members.rb
  * features/support/notes.txt
  * features/support/utils.rb
  * features/android/pages/home_page.rb
  * features/step_definitions/calabash_steps.rb
  * features/step_definitions/global_steps.rb
  * features/step_definitions/home_page.rb

Features:
  * prebuilt/Moda_v2.3.13_com.apk
  * features/header.feature

invalid byte sequence in UTF-8 (ArgumentError)
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:154:in `=~'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:154:in `block in set_encoding'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:153:in `each'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:153:in `set_encoding'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:138:in `initialize'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:132:in `new'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:132:in `read'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:114:in `block in features'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:113:in `map'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:113:in `features'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/canberksevdeger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/canberksevdeger/.rbenv/versions/2.3.1/bin/cucumber:23:in `load'
/Users/canberksevdeger/.rbenv/versions/2.3.1/bin/cucumber:23:in `<main>'
```

**Comment by jmoody** [comment]
@gunesmes 

What is the output of:

```
$ locale
```

Can you try running with:

```
$ LC_ALL="en_US.UTF-8" cucumber -p android prebuilt/Moda_v2.3.13_com.apk features/header.feature  -v
```

**Comment by gunesmes** [comment]
@jmoody 
I also have this error for El Capitan.

at the beginning locale

```
bash-3.2$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

then set the `LC_ALL` 

```
bash-3.2$ export LC_ALL="en_US.UTF-8"
bash-3.2$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

I get the same error, 

```
bash-3.2$ cucumber -p android prebuilt/Moda_v2.3.13_.com.apk  features/M001_top_header.feature   -v
Code:
  * features/support/env.rb
  * features/android/support/app_life_cycle_hooks.rb
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to '/Users/mesutgunes/Android/sdk/'
DEBUG: Set aapt path to '/Users/mesutgunes/Android/sdk/build-tools/24.0.0/aapt'
DEBUG: Set zipalign path to '/Users/mesutgunes/Android/sdk/build-tools/24.0.0/zipalign'
DEBUG: Set adb path to '/Users/mesutgunes/Android/sdk/platform-tools/adb'
DEBUG: Set android jar path to '/Users/mesutgunes/Android/sdk/platforms/android-25/android.jar'
DEBUG: Setting Java SDK location to $JAVA_HOME
DEBUG: Java SDK location set to '/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home'
DEBUG: Found java on PATH
DEBUG: Set java path to '/usr/bin/java'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '/usr/bin/keytool'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '/usr/bin/jarsigner'
  * features/android/support/ids.rb
  * features/android/support/messages.rb
  * features/support/cards.rb
  * features/support/credentials.rb
  * features/support/functions.rb
  * features/support/members.rb
  * features/support/notes.txt
  * features/support/utils.rb
  * features/android/pages/account_page.rb
  * features/android/pages/home_page.rb
  * features/step_definitions/account_page.rb
  * features/step_definitions/calabash_steps.rb
  * features/step_definitions/global_steps.rb
  * features/step_definitions/home_page.rb

Features:
  * prebuilt/Moda_v2.3.13_apkpure.com.apk
  * features/M001_top_header.feature

invalid byte sequence in UTF-8 (ArgumentError)
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:154:in `=~'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:154:in `block in set_encoding'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:153:in `each'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:153:in `set_encoding'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:138:in `initialize'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:132:in `new'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:132:in `read'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:114:in `block in features'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:113:in `map'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:113:in `features'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/mesutgunes/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/mesutgunes/.rbenv/versions/2.3.1/bin/cucumber:23:in `load'
/Users/mesutgunes/.rbenv/versions/2.3.1/bin/cucumber:23:in `<main>'
bash-3.2$
```

**Comment by jmoody** [comment]
What does this yield?

```
$ irb
> str = File.read("features/M001_top_header.feature")
> str.split("\n")
```

After looking at the runtime.rb cucumber ruby, my best guess is that you have a bad character in that feature file.

**Comment by gunesmes** [comment]
it is:

```
bash-3.2$ irb
irb(main):001:0> str = File.read("features/M001_top_header.feature")
=> "Feature: Top Header\n   As An anonymous user\n   I Want to see the top header\n   So That I can interact with the items in it\n\n  Background: Member should open homepage\n    Given I am on the first experience screen\n\n    @header\n    Scenario: I should see items in top head menu\n      Then I should see items in the top head menu\n"
irb(main):002:0>
irb(main):003:0*
irb(main):004:0* str.split("\n")
=> ["Feature: Top Header", "   As An anonymous user", "   I Want to see the top header", "   So That I can interact with the items in it", "", "  Background: Member should open homepage", "    Given I am on the first experience screen", "", "    @header", "    Scenario: I should see items in top head menu", "      Then I should see items in the top head menu"]
irb(main):005:0>
```

**Comment by jmoody** [comment]
Oh.  I think I see the problem:

```
$ cucumber -p android \
  // This is the problem
  prebuilt/Moda_v2.3.13_.com.apk  \
  features/M001_top_header.feature
```

I don't think it is correct to pass the .apk here.

**Comment by gunesmes** [comment]
you are correct, the following command works.

`calabash-android run prebuilt/Moda_v2.3.13_.com.apk -p android features/M001_top_header.feature`

thanks.
