### ISSUE TITLE
Embed is a Cucumber method and is not available for this console

### ISSUE THREAD

**Issue by Bladeclone** [calabash/calabash-android#829]
Calabash-Android Version: 0.9.0

I recently changed my .apk file to a later version and have now noticed that I get an error anytime I try to query webview CSS.

```
irb(main):008:0> query("webView css:'#header'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map webView css:'#header', query failed because: java.util.concurrent.TimeoutException: Timeout while waiting for value
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:962:in `screenshot_and_raise'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:1355:in `map'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:233:in `query'        from (irb):8
        from C:/Ruby21/bin/irb:11:in `<main>'
```

However, I can run queries like query "button" no problem, I'm only getting an error with webview css which is strange because the scripts worked fine before I changed the .apk.
I ran calabash-android resign and calabash-android build without errors so I really don't know why I am having this problem. I'm sure it has something to do with the .apk but I really don't know anything about it as I didn't develop it, I'm merely trying to test.

Thanks.

**Comment by jmoody** [comment]
> Embed is a Cucumber method and is not available in this console.

This is not an error.  It is our attempt to explain why a screenshot is not taken.  I wonder if we should remove it; it seems to generate confusion and GitHub issues.

```
RuntimeError: map webView css:'#header', query failed because: 
java.util.concurrent.TimeoutException: Timeout while waiting for value
```

^ that is the error.

My Calabash Android fu is really weak, but are you sure that is the correct syntax for an Android web view query?

```
# Looks like iOS UIWebView query...I am probably mistaken.
> query("webView css:'#header'")

# Does this work?
> query("* css:'#header'")
```

**Comment by Bladeclone** [comment]
Thanks for the quick response.
Well, I have not changed the syntax and it worked before, I have tried many different variations, including your examples and still I get the same errors. This is most unusual as I can query the webview itself and see that it does in fact exist but I can't query the css AT ALL. 
Very confused that it previously worked before changing the .apk

```
irb(main):012:0> query("* css:'#header'")
Embed is a Cucumber method and is not available in this console.
RuntimeError: map * css:'#header', query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.internal.policy.impl.PhoneWindow.DecorView is not recognized a valid web view.

        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:962:in `screenshot_and_raise'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:1355:in `map'
        from C:/Ruby21/lib/ruby/gems/2.1.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:233:in `query'
        from (irb):12
        from C:/Ruby21/bin/irb:11:in `<main>'
```

**Comment by Bladeclone** [comment]
It is perhaps important to note that I was not seeing the Embed error beforehand either

**Comment by jmoody** [comment]
>  Embed error beforehand either

Cucumber `embed` is called when a query raises an error, so you would not see this message _unless_ there is an error.

Someone with more Android fu is going need to answer this.

**Comment by darkash** [comment]
how about this?

`query("android.webkit.WebView css:'#header'")`

somehow I can't query webview using the aforementioned method, but this one works.
