### ISSUE TITLE
calabash-android build failed with eval_gemfile

### ISSUE THREAD

**Issue by darkash** [calabash/calabash-android#832]
hello, I am using calabash to do our application test and it fails upon using the gemfile with "eval_gemfile" in it, meanwhile it succeed in creating test server when using gemfile without "eval_gemfile"

bundle install is fine, but I don't know why it fails on calabash saying bundler cannot continue

The error message:
```
[!] There was an error parsing `Gemfile`: 
[!] There was an error parsing `GemfileDefault`: No such file or directory @ rb_sysopen - GemfileDefault. Bundler cannot continue.
. Bundler cannot continue.

 #  from /Users/USER/calabash/Gemfile:2
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  eval_gemfile('GemfileDefault')
 #  gem 'activerecord', '~> 3.2.11'
 #  -------------------------------------------

/Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:42:in `block (2 levels) in calabash_build': Could not replace package name in manifest (RuntimeError)
	from /Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:37:in `chdir'
	from /Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:37:in `block in calabash_build'
	from /Users/USER/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
	from /Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/bin/calabash-android-build.rb:36:in `calabash_build'
	from /Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:107:in `build_test_server_if_needed'
	from /Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/bin/calabash-android-console.rb:26:in `calabash_console'
	from /Users/USER/.rvm/gems/ruby-2.1.5/gems/calabash-android-0.9.0/bin/calabash-android:107:in `<top (required)>'
	from /Users/USER/.rvm/gems/ruby-2.1.5/bin/calabash-android:23:in `load'
	from /Users/USER/.rvm/gems/ruby-2.1.5/bin/calabash-android:23:in `<main>'
	from /Users/USER/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/USER/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

```

Is there a way to solve this? Thank you

**Comment by darkash** [comment]
nvm, silly me the eval_gemfile used the relative path and has nothing to do with calabash, tho it still intrigues me why it still fails in calabash-android build while bundle install does this without any problem
