### ISSUE TITLE
App didnt start

### ISSUE THREAD

**Issue by nnukala** [calabash/calabash-android#836]
Starting calabash-android console...
Loading C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/irbrc
Running irb...
The system cannot find the path specified.

irb(main):003:0> start_test_server_in_background
The system cannot find the path specified.
RuntimeError: Could not execute command to start test server
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:734:in `start_test_server_in_background'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:152:in `start_test_server_in_background'
        from (irb):3
        from C:/Ruby23/bin/irb.cmd:19:in `<main>'
irb(main):004:0> exit

Adb Logs:
I/ActivityManager(  553): Killing 6397:com.citipush/u0a637 (adj 0): stop com.citipush
W/ActivityManager(  553): Crash of app com.citipush running instrumentation ComponentInfo{com.citipush.test/sh.calaba.instrumentationbackend.CalabashInstrumentat
D/AndroidRuntime( 6481): Shutting down VM
D/dalvikvm( 6481): GC_CONCURRENT freed 100K, 14% free 667K/772K, paused 0ms+0ms, total 3ms
E/lights  (  553): write_int failed to open -1
I/dalvikvm( 6496): Could not find method android.app.Instrumentation.execStartActivity, referenced from method sh.calaba.exposed.InstrumentationExposed.execStart
W/dalvikvm( 6496): VFY: unable to resolve virtual method 38: Landroid/app/Instrumentation;.execStartActivity (Landroid/content/Context;Landroid/os/IBinder;Landro
D/dalvikvm( 6496): VFY: replacing opcode 0x75 at 0x0000
I/dalvikvm( 6496): Could not find method android.app.Instrumentation.execStartActivity, referenced from method sh.calaba.exposed.InstrumentationExposed.execStart
W/dalvikvm( 6496): VFY: unable to resolve virtual method 41: Landroid/app/Instrumentation;.execStartActivity (Landroid/content/Context;Landroid/os/IBinder;Landro
D/dalvikvm( 6496): VFY: replacing opcode 0x75 at 0x0000
I/dalvikvm( 6496): Could not find method android.app.Instrumentation.execStartActivityAsCaller, referenced from method sh.calaba.exposed.InstrumentationExposed.e
W/dalvikvm( 6496): VFY: unable to resolve virtual method 43: Landroid/app/Instrumentation;.execStartActivityAsCaller (Landroid/content/Context;Landroid/os/IBinde
D/dalvikvm( 6496): VFY: replacing opcode 0x75 at 0x0000
I/MultiDex( 6496): VM with version 1.6.0 does not have multidex support
I/MultiDex( 6496): install
I/MultiDex( 6496): MultiDexExtractor.load(/data/app/com.citipush-1.apk, false)
I/MultiDex( 6496): loading existing secondary dex files
I/MultiDex( 6496): load found 2 secondary dex files
I/MultiDex( 6496): install done
I/MultiDex( 6496): install
I/System.out( 6496): Main activity name automatically set to: com.citipush.MainActivity
I/System.out( 6496): Calabash did not load Mono. This is only a problem if you are trying to test a Mono application
I/calabash( 6496): Test server port: 7102
I/InstrumentationBackend( 6496): Added:'NullAction', with key:'nullAction'
I/InstrumentationBackend( 6496): Added:'GetActivityOrientation', with key:'get_activity_orientation'
I/InstrumentationBackend( 6496): Added:'SetActivityOrientation', with key:'set_activity_orientation'
I/InstrumentationBackend( 6496): Added:'DpToDevicePixel', with key:'dp_to_device_pixel'
I/InstrumentationBackend( 6496): Added:'ClickOnScreen', with key:'click_on_screen'
I/InstrumentationBackend( 6496): Added:'DoubleTapCoordinate', with key:'double_tap_coordinate'
I/InstrumentationBackend( 6496): Added:'Drag', with key:'drag'
I/InstrumentationBackend( 6496): Added:'DragCoordinates', with key:'drag_coordinates'
I/InstrumentationBackend( 6496): Added:'LongPressCoordinate', with key:'long_press_coordinate'
I/InstrumentationBackend( 6496): Added:'ResumeApplication', with key:'resume_application'
I/InstrumentationBackend( 6496): Added:'Swipe', with key:'swipe'
I/InstrumentationBackend( 6496): Added:'TouchCoordinates', with key:'touch_coordinate'
I/InstrumentationBackend( 6496): Added:'ListActions', with key:'list_actions'
I/InstrumentationBackend( 6496): Added:'SendTcp', with key:'send_tcp'
I/InstrumentationBackend( 6496): Added:'PressElement', with key:'press_l10n_element'
I/InstrumentationBackend( 6496): Added:'WaitForElement', with key:'wait_for_l10n_element'
I/InstrumentationBackend( 6496): Added:'FakeGPSLocation', with key:'set_gps_coordinates'
I/InstrumentationBackend( 6496): Added:'GetMapBounds', with key:'get_map_bounds'
I/InstrumentationBackend( 6496): Added:'GetMapCenter', with key:'get_map_center'
I/InstrumentationBackend( 6496): Added:'GetMapMarker', with key:'get_map_marker'
I/InstrumentationBackend( 6496): Added:'GetMapMarkers', with key:'get_map_markers'
I/InstrumentationBackend( 6496): Added:'GetMapZoom', with key:'get_map_zoom'
I/InstrumentationBackend( 6496): Added:'PanMapTo', with key:'pan_map_to'
I/InstrumentationBackend( 6496): Added:'SetMapCenter', with key:'set_map_center'
I/InstrumentationBackend( 6496): Added:'SetMapZoom', with key:'set_map_zoom'
I/InstrumentationBackend( 6496): Added:'TapAwayFromMarkers', with key:'tap_map_away_from_markers'
I/InstrumentationBackend( 6496): Added:'TapMapMarker', with key:'tap_map_marker_by_title'
I/InstrumentationBackend( 6496): Added:'ClearPreferences', with key:'clear_preferences'
I/InstrumentationBackend( 6496): Added:'GetPreferences', with key:'get_preferences'
I/InstrumentationBackend( 6496): Added:'SetPreferences', with key:'set_preferences'
I/InstrumentationBackend( 6496): Added:'PressKey', with key:'press_key'
I/InstrumentationBackend( 6496): Added:'DeleteSurroundingText', with key:'delete_surrounding_text'
I/InstrumentationBackend( 6496): Added:'HideSoftKeyboard', with key:'hide_soft_keyboard'
I/InstrumentationBackend( 6496): Added:'KeyboardEnterText', with key:'keyboard_enter_text'
I/InstrumentationBackend( 6496): Added:'KeyboardKeyEvent', with key:'keyboard_key_event'
I/InstrumentationBackend( 6496): Added:'PressUserActionButton', with key:'press_user_action_button'
I/InstrumentationBackend( 6496): Added:'SetComposingRegion', with key:'set_composing_region'
I/InstrumentationBackend( 6496): Added:'SetSelection', with key:'set_selection'
I/InstrumentationBackend( 6496): Added:'AndroidSDKVersion', with key:'android_sdk_version'
I/InstrumentationBackend( 6496): Added:'Version', with key:'version'
I/InstrumentationBackend( 6496): Added:'GetActivityName', with key:'get_activity_name'
I/InstrumentationBackend( 6496): Added:'IsCurrentActivityFocused', with key:'is_current_activity_focused'
I/InstrumentationBackend( 6496): Added:'ScrollToView', with key:'scroll_to_view'
I/InstrumentationBackend( 6496): Added:'ViewConfiguration', with key:'view_configuration'
I/InstrumentationBackend( 6496): Added:'DumpBodyHtml', with key:'dump_body_html'
I/InstrumentationBackend( 6496): Added:'DumpHtml', with key:'dump_html'
I/InstrumentationBackend( 6496): Added:'EnterTextByCssSelector', with key:'enter_text_by_selector'
I/InstrumentationBackend( 6496): Added:'GetLoadProgress', with key:'get_load_progress'
I/InstrumentationBackend( 6496): Added:'GetUrl', with key:'get_url'
I/InstrumentationBackend( 6496): Added:'ScrollTo', with key:'scroll_to'
I/InstrumentationBackend( 6496): Added:'SetPropertyByCssSelector', with key:'set_property_by_css_selector'
I/calabash( 6496): Instantiating http server at 7102
I/System.out( 6496): HTTP Daemon listening on: 7102
W/ActivityManager(  553): Permission Denial: getCurrentUser() from pid=6496, uid=10637 requires android.permission.INTERACT_ACROSS_USERS

**Comment by NahidSiddiqui** [comment]
Please confirm the following steps:

1. Ensure the apk is installed on the device
2. Ensure the keystore for the app project is present on the directory from which you are running the "calabash-android console apk" command
3. The correct command for calabash-android should be as below:

calabash-android console full path to the apk file

The keystore can be provided by your developers, it can be found in the app project directory

**Comment by nnukala** [comment]
Sorry for the late reply.

I am just running the calabash console using the above command as you mentioned.
