### ISSUE TITLE
Can't resing apk

### ISSUE THREAD

**Issue by alexsfry1** [calabash/calabash-android#838]
Hello.

I can't resign apk, after enter calabash-android resign .\debug.apk -v command, i take this massege 

 calabash-android resign .\debug.apk -v
2017-08-23 13:04:26 - Resign apk
DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to 'E:\AndroidSDK'

DEBUG: Set aapt path to 'E:\AndroidSDK/build-tools/26.0.1/aapt.exe'
DEBUG: Set zipalign path to 'E:\AndroidSDK/build-tools/26.0.1/zipalign.exe'
DEBUG: Set adb path to 'E:\AndroidSDK/platform-tools/adb.exe'
DEBUG: Set android jar path to 'E:\AndroidSDK/platforms/android-26/android.jar'
DEBUG: Setting Java SDK location to $JAVA_HOME
DEBUG: Java SDK location set to 'C:\Program Files\Java\jdk1.8.0_121'
DEBUG: Found java on PATH
DEBUG: Set java path to '\ProgramData\Oracle\Java\javapath/java.exe'
DEBUG: Set keytool path to 'C:\Program Files\Java\jdk1.8.0_121/bin/keytool.exe'
DEBUG: Set jarsigner path to 'C:\Program Files\Java\jdk1.8.0_121/bin/jarsigner.exe'
2017-08-23 13:04:27 - Keystore location specified in .calabash_settings.
2017-08-23 13:04:27 - Reading keystore data from keystore file 'C:/Users/a.chetverikov/.android'
2017-08-23 13:04:27 - "C:\Program Files\Java\jdk1.8.0_121/bin/keytool.exe" -list -v -alias "" -keystore C:/Users/a.chetverikov/.android -storepass "" "-J"-Dfile.encoding=utf-8"" "-J"-Duser.language=en-US""
2017-08-23 13:04:27 - Could not obtain keystore data. Will try to extract alias automatically
2017-08-23 13:04:27 - "C:\Program Files\Java\jdk1.8.0_121/bin/keytool.exe" -list -v -keystore C:/Users/a.chetverikov/.android -storepass "" "-J"-Dfile.encoding=utf-8"" "-J"-Duser.language=en-US""
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:16:in `initialize': undefined method `scan' for nil:NilClass (NoMethodError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:116:in `new'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:116:in `keystore_from_settings'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/java_keystore.rb:95:in `get_keystores'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:158:in `sign_apk'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:119:in `block in resign_apk'
        from C:/Ruby24-x64/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/helpers.rb:113:in `resign_apk'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/calabash-android-0.9.0/bin/calabash-android:133:in `<top (required)>'
        from C:/Ruby24-x64/bin/calabash-android:22:in `load'
        from C:/Ruby24-x64/bin/calabash-android:22:in `<main>'

**Comment by alxhotel** [comment]
@alexsfry1 did you solved the issue?
