### ISSUE TITLE
Unable to load the watir in cucumber

### ISSUE THREAD

**Issue by nnukala** [calabash/calabash-android#846]
QACommon:~ qausr$ gem list

*** LOCAL GEMS ***
watir (6.9.1)
watir-webdriver (0.9.9)

Console:
qausr$ cucumber
cannot load such file -- watir (LoadError)
/Users/qausr/Documents/Naga/I_CitiPhase1/features/steps/CommonSteps.rb:2:in `require'
/Users/qausr/Documents/Naga/I_CitiPhase1/features/steps/CommonSteps.rb:2:in `<top (required)>'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:106:in `load'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:106:in `load_code_file'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/runtime/support_code.rb:147:in `load_file'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/runtime/support_code.rb:88:in `block in load_files!'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/runtime/support_code.rb:87:in `each'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/runtime/support_code.rb:87:in `load_files!'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:270:in `load_step_definitions'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:67:in `run!'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/qausr/.rvm/gems/ruby-2.2.1/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
/Users/qausr/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `load'
/Users/qausr/.rvm/gems/ruby-2.2.1/bin/cucumber:23:in `<main>'
/Users/qausr/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/qausr/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by nnukala** [comment]
I found the root cause for it. Even If I didn't run the cucumber command using the bundle exec, it is checking the watir gem in the BUNDLE instead of GLOBAL GEM location. Later I installed the watir into bundle and everything id fine.
