### ISSUE TITLE
calabash-android run error: 

### ISSUE THREAD

**Issue by yiyiguzhou** [calabash/calabash-android#848]
I run calabash and occurred a error
  
Scenario: As a valid user I can log into my app # features/my_first - ?feature
:3m
    When I press "Login"                          # calabash-android-0.9.0/lib/c
alabash-android/steps/press_button_steps.rb:17
      Timeout waiting for elements: * marked:'Login' (Calabash::Android::WaitHel
pers::WaitError)
      features/my_first - ?feature:4:in `When I press "Login"'m
    Then I see "Welcome to coolest app ever"      # calabash-android-0.9.0/lib/c
alabash-android/steps/assert_steps.rb:5

**Feature: No space left on device @ io_write - <STDOUT> (Errno::ENOSPC)**
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/pretty.rb:72:in `write'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/pretty.rb:72:in `puts'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/pretty.rb:72:in `feature_name'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/ignore_missing_messages.rb:11:in `method_missing'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/legacy_api/adapter.rb:231:in `before'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/legacy_api/adapter.rb:117:in `feature'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/ast/describes_itself.rb:7:in `describe_to'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/test/case.rb:37:in `block in describe_source_to'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/test/case.rb:36:in `each'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/test/case.rb:36:in `describe_source_to'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/legacy_api/adapter.rb:98:in `before_test_case'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-3.1.0/lib/cucumber
/formatter/legacy_api/adapter.rb:23:in `block in initialize'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/event_bus.rb:34:in `call'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/event_bus.rb:34:in `block in broadcast'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/event_bus.rb:34:in `each'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/event_bus.rb:34:in `broadcast'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/event_bus.rb:40:in `method_missing'
E:/Program Files/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cucumber-core-3.1.0/lib/cuc
umber/core/test/runner.rb:18:in `test_case'
...

and my_first.feature content just start an app and take a screenshot

**Comment by sherbhachu** [comment]
I don't quite understand the issue here.

Can you verify that the element marked 'Login' does indeed exist?

Other than that, it simply looks like that you don't have enough disk space for the process to run/start .... does that process have the necessary permissions to create/add/edit the 'E' drive?
