### ISSUE TITLE
calabash-android resign error (No signature algorithm names found)

### ISSUE THREAD

**Issue by cassiaoliveira** [calabash/calabash-android#859]
When I run this command on the Windows:
calabash-android resign nomeDoApk.apk 

It shows this message:
 
C:\Calabash\AZUL>calabash-android resign nomeDoApk.apk
Traceback (most recent call last):
        11: from C:/Ruby25-x64/bin/calabash-android:23:in `<main>'
        10: from C:/Ruby25-x64/bin/calabash-android:23:in `load'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/b
in/calabash-android:133:in `<top (required)>'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/helpers.rb:113:in `resign_apk'
         7: from C:/Ruby25-x64/lib/ruby/2.5.0/tmpdir.rb:89:in `mktmpdir'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/helpers.rb:119:in `block in resign_apk'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/helpers.rb:158:in `sign_apk'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/java_keystore.rb:95:in `get_keystores'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/java_keystore.rb:116:in `keystore_from_settings'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/java_keystore.rb:116:in `new'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/l
ib/calabash-android/java_keystore.rb:42:in `initialize'
**C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/calabash-android-0.9.2/lib/calabash-andro
id/helpers.rb:215:in `extract_signature_algorithm_name': No signature algorithm
names found: (RuntimeError)**
 Alias name: azul-tec
Creation date: Dec 13, 2016
Entry type: keyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=Caio Cesar Fantini, OU=Online Applications, O=Online Group, L=Campinas
, ST=S├úo Paulo
Issuer: CN=Caio Cesar Fantini, OU=Online Applications, O=Online Group, L=Campina
s, ST=S├úo Paulo
Serial number: 24cd62a9
Valid from: Tue Dec 13 10:09:05 BRST 2016 until: Sat Dec 07 10:09:05 BRST 2041
Certificate fingerprints:
         MD5:  D4:B1:66:39:A2:D1:36:E1:5D:21:0D:92:2A:B2:BF:4F
         SHA1: 3F:B6:3E:1E:3A:FB:C7:D5:09:95:4A:D2:E2:C5:58:41:79:F5:D2:A9

Somebody can help me to find what it´s wrong?
Best regards

**Comment by wellavelino** [comment]
@cassiaoliveira im not sure about that, can you send your stack version?
This erros happens only with this apk?
