### ISSUE TITLE
E/zip     ( 1744): error during crunch - archive is toast - while resign the apk

### ISSUE THREAD

**Issue by prabhudorairaj85** [calabash/calabash-android#862]
can you help me to debug this issue, while trying to resign the apk.

i have changed the debug keystore and also signed new keystore.it didnt solve the problem
currently runing calabash-android version 
0.9.2

DEBUG: Setting Android SDK location to $ANDROID_HOME
DEBUG: Android SDK location set to 'C:\Android'
DEBUG: Set aapt path to 'C:\Android/build-tools/23.0.3/aapt.exe'
DEBUG: Set zipalign path to 'C:\Android/build-tools/23.0.3/zipalign.exe'
DEBUG: Set adb path to 'C:\Android/platform-tools/adb.exe'
DEBUG: Set android jar path to 'C:\Android/platforms/android-23/android.jar'
DEBUG: Setting Java SDK location to $JAVA_HOME
DEBUG: Java SDK location set to 'C:\Program Files\Java\jre1.8.0_161\'
DEBUG: Found java on PATH
DEBUG: Set java path to '\ProgramData\Oracle\Java\javapath/java.exe'
DEBUG: Found keytool on PATH
DEBUG: Set keytool path to '\Program Files\Java\jdk1.8.0_73\bin/keytool.exe'
DEBUG: Found jarsigner on PATH
DEBUG: Set jarsigner path to '\Program Files\Java\jdk1.8.0_73\bin/jarsigner.exe'
E/zip     ( 1744): error during crunch - archive is toast
2018-02-13 17:45:28 - Reading keystore data from keystore file 'C:/Users/dorairaj01/.android/debug.keystore'
2018-02-13 17:45:28 - "\Program Files\Java\jdk1.8.0_73\bin/keytool.exe" -list -v -alias androiddebugkey -keystore C:/Users/dorairaj01/.android/debug.keystore -storepass android "-J"-Dfile.encoding=utf-8"" "-J"-Duser.language=en-US""
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
2018-02-13 17:45:29 - Key store data:
2018-02-13 17:45:29 - Alias name: androiddebugkey
Creation date: Feb 22, 2016
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=Android Debug, O=Android, C=US
Issuer: CN=Android Debug, O=Android, C=US
Serial number: 6b84c43
Valid from: Mon Feb 22 11:02:44 CET 2016 until: Wed Feb 14 11:02:44 CET 2046
Certificate fingerprints:
         MD5:  CA:99:E2:C0:0D:15:99:D6:CA:70:3E:85:CB:44:B4:44
         SHA1: BC:24:84:A2:D4:52:24:05:75:96:ED:1D:FE:4A:7B:54:97:E0:AF:E4
         SHA256: F7:7A:38:29:BE:1E:89:F5:7E:4E:7C:3B:88:4E:FE:24:F7:4F:E6:93:D2:42:44:88:1B:D8:B1:71:2C:49:2A:B5
         Signature algorithm name: SHA256withRSA
         Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 70 96 B1 D4 17 EE E0 52   E5 90 CC 9A B2 5A 75 DB  p......R.....Zu.
0010: 28 C8 12 B3                                        (...
]
]

2018-02-13 17:45:29 - Fingerprint: D4:52:24:05:75:96:ED:1D:FE:4A:7B:54:97:E0:AF:E4
2018-02-13 17:45:29 - Signature algorithm name: SHA256withRSA
2018-02-13 17:45:29 - Unlocked keystore at C:/Users/dorairaj01/.android/debug.keystore - fingerprint: D4:52:24:05:75:96:ED:1D:FE:4A:7B:54:97:E0:AF:E4
2018-02-13 17:45:29 - Trying to read keystore from: c:/zappAutotest/automation/debug.keystore - no such file
2018-02-13 17:45:29 - Trying to read keystore from: C:/Users/dorairaj01/.local/share/Xamarin/Mono/ for/ Android/debug.keystore - no such file
2018-02-13 17:45:29 - Trying to read keystore from: C:/Users/dorairaj01/AppData/Local/Xamarin/Mono for Android/debug.keystore - no such file
2018-02-13 17:45:29 - Signing using the signature algorithm: 'SHA1withRSA'
2018-02-13 17:45:29 - Signing using the digest algorithm: 'SHA1'
2018-02-13 17:45:29 - "\Program Files\Java\jdk1.8.0_73\bin/jarsigner.exe" -sigfile CERT -sigalg SHA1withRSA -digestalg SHA1 -signedjar "C:/Users/DORAIR~1/AppData/Local/Temp/d20180213-3832-1dxfku8/unaligned.apk" -storepass android -keystore C:/Users/dorairaj01/
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.2/lib/calabash-android/java_keystore.rb:60:in `sign_apk': Could not sign app: C:/Users/DORAIR~1/AppData/Local/Temp/d20180213-3832-1dxfku8/unsigned.apk (RuntimeError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.2/lib/calabash-android/helpers.rb:164:in `sign_apk'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.2/lib/calabash-android/helpers.rb:119:in `block in resign_apk'
        from C:/Ruby23/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.2/lib/calabash-android/helpers.rb:113:in `resign_apk'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/calabash-android-0.9.2/bin/calabash-android:133:in `<top (required)>'
        from C:/Ruby193/bin/calabash-android:23:in `load'
        from C:/Ruby193/bin/calabash-android:23:in `<main>'

**Comment by mreid-projects** [comment]
I'm experiencing that problem too, how did you solve it @prabhudorairaj85 ?

**Comment by prabhudorairajvimla** [comment]
@mreid-projects i just downgraded the calabash version .

**Comment by alondero** [comment]
What version did you downgrade to @prabhudorairajvimla ?
