### ISSUE TITLE
click_on_screen doesn't working

### ISSUE THREAD

**Issue by aluckin3** [calabash/calabash-android#884]
Is there any reason why this function doesn't work (click is not performed and there is no error):
perform_action('click_on_screen', x, y) 
or touch_coordinate doesn't work at all

For click on screen i get this:
{
    "bonusInformation" => [],
             "message" => "",
             "success" => true
}

For touch_coordinate:
       10: from /Users/amar/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        9: from (irb):8
        8: from /Users/amar/.rvm/gems/ruby-2.5.1/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:93:in `perform_action'
        7: from /Users/amar/.rvm/gems/ruby-2.5.1/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:445:in `perform_action'
        6: from /Users/amar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
        5: from /Users/amar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `catch'
        4: from /Users/amar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `catch'
        3: from /Users/amar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
        2: from /Users/amar/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
        1: from /Users/amar/.rvm/gems/ruby-2.5.1/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:456:in `block in perform_action'
RuntimeError (Action 'touch_coordinate' unsuccessful: Click can not be completed!)

**Comment by AndreyMitsyk** [comment]
Hi @aluckin3 , could you please try to use latest calabash-android gem 0.9.5? If this error will be reproduced with latest version, please provide more info about android version where you have test apk.

**Comment by aluckin3** [comment]
It doesnt touch on webView, i think, but there is no error on 0.9.5

**Comment by AndreyMitsyk** [comment]
@aluckin3 In 0.9.5 we have massive changes. So if it's ok with 0.9.5 please close this issue.
