### ISSUE TITLE
All WebView methods must be called on the same thread.

### ISSUE THREAD

**Issue by aluckin3** [calabash/calabash-android#885]
map webView css:'button[type="submit"]' {textContent CONTAINS 'Sign inContinue'}, query failed because: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'Thread-110'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {24a3362} called on null, FYI main Looper is Looper (main, tid 2) {24a3362})
       (RuntimeError)
      ./step_definitions/android/screens/base.rb:48:in `wait_until_element_disappear'
      ./step_definitions/android/screens/base.rb:13:in `block (3 levels) in log_me'
      ./step_definitions/android/screens/base.rb:134:in `pcloud_finish_login'
      ./step_definitions/android/screens/dropbox_login_page.rb:28:in `sign_in'
      ./step_definitions/android/screens/base.rb:13:in `block (3 levels) in log_me'
      ./step_definitions/pcloud_steps.rb:14:in `/^I login to (GoogleDrive|Dropbox|OneDrive)$/'
      features/sync/trigger.feature:34:in `And I login to Dropbox'
      features/sync/trigger.feature:17:in `And I login to <pcloud>'

Is it possible to avoid this problem?

**Comment by AndreyMitsyk** [comment]
Interesting... Please provide some info: Which Android version was used for this test run? Is it Android P (api 28) on Emulator/physical device? One more question: are your test scenarios trying to enter some text on webview?

**Comment by aluckin3** [comment]
This is api 26, on emulator. Yes, application is about api of services and application.
