### ISSUE TITLE
App Did Not start error in One Plus 3 phone running on Android 8.0 (OREO)

### ISSUE THREAD

**Issue by gururaja-bhat** [calabash/calabash-android#891]
Calabash logs

2018-09-03 02:48:10 - It looks like your app is no longer running. 
It could be because of a crash or because your test script shut it down.
RuntimeError: App did not start
	from /Users/gururajabhats/.rvm/gems/ruby-2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:737:in `block in start_test_server_in_background'
	from /Users/gururajabhats/.rvm/gems/ruby-2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/retry.rb:10:in `block in retry'
	from /Users/gururajabhats/.rvm/gems/ruby-2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/retry.rb:8:in `times'
	from /Users/gururajabhats/.rvm/gems/ruby-2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/retry.rb:8:in `retry'
	from /Users/gururajabhats/.rvm/gems/ruby-2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:736:in `start_test_server_in_background'
	from /Users/gururajabhats/.rvm/gems/ruby-2.4.0/gems/calabash-android-0.9.0/lib/calabash-android/operations.rb:152:in `start_test_server_in_background'
	from (irb):1
	from /Users/gururajabhats/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'

*adb logs*

09-03 02:57:34.068 17533 17533 E adbd    : failed to connect to socket 'tcp:7103': Connection refused
09-03 02:57:34.177 17533 17533 I chatty  : uid=2000(shell) /sbin/adbd identical 2 lines
09-03 02:57:34.181 17533 17533 E adbd    : failed to connect to socket 'tcp:7103': Connection refused
09-03 02:57:34.199  3232 22230 I TachyonSyncUtils: removeSyncAccount. Success: true
09-03 02:57:34.291 17533 17533 E adbd    : failed to connect to socket 'tcp:7103': Connection refused
09-03 02:57:34.750 17533 17533 I chatty  : uid=2000(shell) /sbin/adbd identical 8 lines
09-03 02:57:34.756 17533 17533 E adbd    : failed to connect to socket 'tcp:7103': Connection refused

I am using calabash-android version 0.9.0. I tried with the latest version too but it didnot work on OREO device. It worked well on Android device running on Marshmallow

**Comment by gunesmes** [comment]
Hi @gururaja-bhat, 
have you solved the problem? 

I got the same error. Checked it in the adb log Calabash server gives an runtime exception during start:

```
09-12 10:40:51.245 27719 27719 I calabash: Test server port: 7102
09-12 10:40:51.252  3741  3938 I ActivityManager: START u0 {act=null typ=null flg=0x10000000 cmp=ComponentInfo{app.testapp.test/sh.calaba.instrumentationbackend.StatusReporterActivity}} from uid 10283 on display 0
09-12 10:40:51.255  3741  3938 D ActivityManager: ActivityRecord() Constructor : multiScreenAttrs=MultiScreenAttrs{mDisplayId=0, mBaseDisplayId=0, mBaseActivity=false}
09-12 10:40:51.257  3741  3938 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1560000  uid : 1000  pid : 3741  pkgName : AMS_RESUME@CPU_MIN@7
09-12 10:40:51.258  3741  3938 D ActivityManager: mActivityResumeBooster.acquire()
09-12 10:40:51.258  3741  3938 D ActivityManager: computeStackFocus: stackId=1
09-12 10:40:51.258  3741  3938 D MultiScreenManagerService: createStack: stackId=1 createOnTop=true caller=com.android.server.am.ActivityStackSupervisor.getStack:2407 com.android.server.am.ActivityStarter.computeStackFocus:2487 com.android.server.am.ActivityStarter.setTaskFromReuseOrCreateNewTask:2178 com.android.server.am.ActivityStarter.startActivityUnchecked:1449 
09-12 10:40:51.258  3741  3938 D ActivityManager: attachDisplay() : attach stack#1 to d0
09-12 10:40:51.258  3741  3938 D MultiScreenManagerService: createStack: stackId=1 displayId=0 createOnTop=true
09-12 10:40:51.258  3741  3938 D MultiScreenManagerService: createStack: stack=ActivityStack{7699f17d0 stackId=1, 0 tasks}
09-12 10:40:51.258  3741  3938 D ActivityManager: computeStackFocus: New stack r=ActivityRecord{93bef04d0 u0 app.testapp.test/sh.calaba.instrumentationbackend.StatusReporterActivity t-1} stackId=1
09-12 10:40:51.259  3741  3938 I MultiWindowManagerService: setTaskDimensions: Task=TaskRecord{10af770d0 #47 A=app.testapp.test U=0 StackId=1 sz=1} minWidth=-1 minHeight=-1 maxWidth=-1 maxHeight=-1
09-12 10:40:51.259  3741  3938 D ActivityManager: moveToFront() : reason=startedActivity setFocusedActivity isAttached=true TaskRecord{10af770d0 #47 A=app.testapp.test U=0 StackId=1 sz=1}
09-12 10:40:51.260  3741  3938 D ActivityManager: setFocusStackUnchecked: reason=startedActivity setFocusedActivity focusCandidate=ActivityStack{7699f17d0 stackId=1, 1 tasks} caller=com.android.server.am.ActivityStack.moveToFront:875 com.android.server.am.ActivityStackSupervisor.moveActivityStackToFront:1995 
09-12 10:40:51.261  3741  3938 D InputDispatcher: Focused application set to: xxxx
09-12 10:40:51.261  3741  3938 D InputDispatcher: Focus left window: 4871
09-12 10:40:51.262  3741  3938 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{10af770d0 #47 A=app.testapp.test U=0 StackId=1 sz=1} next=ActivityRecord{93bef04d0 u0 app.testapp.test/sh.calaba.instrumentationbackend.StatusReporterActivity t47} mFocusedStack=ActivityStack{7699f17d0 stackId=1, 1 tasks}
09-12 10:40:51.262  3741  3938 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
09-12 10:40:51.262  3741  3938 D GameManagerService: sem_perfomance_mode: 0
09-12 10:40:51.263  4871  4871 D Launcher: onPause, Launcher: 77391524
09-12 10:40:51.263  4871  4871 D Launcher.HomeView: onPause
09-12 10:40:51.263  4871  4871 D Launcher.Workspace: exitWidgetResizeMode. isClearResizeFrame is false
09-12 10:40:51.263  3741  3938 D LockSettingsStorage: mSKTLockState = 2
09-12 10:40:51.265 27719 27719 D AndroidRuntime: Shutting down VM
09-12 10:40:51.266  3741  3815 D WindowManager: addWindow: android.view.ViewRootImpl$W@c4d882b displayId=0
09-12 10:40:51.266 27719 27719 E AndroidRuntime: FATAL EXCEPTION: main
09-12 10:40:51.266 27719 27719 E AndroidRuntime: Process: app.testapp, PID: 27719
09-12 10:40:51.266 27719 27719 E AndroidRuntime: java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{app.testapp.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}: java.lang.RuntimeException: java.io.FileNotFoundException: actions
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: actions
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.actions.Actions.loadActions(Actions.java:44)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.actions.Actions.<init>(Actions.java:29)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.entrypoint.AndroidInstrumentationStartup.setup(AndroidInstrumentationStartup.java:122)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.entrypoint.AndroidInstrumentationStartup.start(AndroidInstrumentationStartup.java:93)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.Main.start(Main.java:10)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.CalabashInstrumentation.onCreate(CalabashInstrumentation.java:34)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	... 8 more
09-12 10:40:51.266 27719 27719 E AndroidRuntime: Caused by: java.io.FileNotFoundException: actions
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.content.res.AssetManager.openAsset(Native Method)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:421)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:395)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.actions.Actions.loadActions(Actions.java:34)
09-12 10:40:51.266 27719 27719 E AndroidRuntime: 	... 14 more
```

**Comment by gunesmes** [comment]
hi @AndreyMitsyk It gives the same error. Log is in the below. But removing the instrument_backend and using calabash-android 0.9.5 with rubyzip 1.2.1 works well.

```
09-13 13:38:24.101 30348 30348 I calabash: Test server port: 7102
09-13 13:38:24.108  3741 11514 I ActivityManager: START u0 {act=null typ=null flg=0x10000000 cmp=ComponentInfo{app.testapp.test/sh.calaba.instrumentationbackend.StatusReporterActivity}} from uid 10294 on display 0
09-13 13:38:24.111  3741 11514 D ActivityManager: ActivityRecord() Constructor : multiScreenAttrs=MultiScreenAttrs{mDisplayId=0, mBaseDisplayId=0, mBaseActivity=false}
09-13 13:38:24.112  3741 11514 D CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1560000  uid : 1000  pid : 3741  pkgName : AMS_RESUME@CPU_MIN@7
09-13 13:38:24.113  3741 11514 D ActivityManager: mActivityResumeBooster.acquire()
09-13 13:38:24.116  3741 11514 I MultiWindowManagerService: setTaskDimensions: Task=TaskRecord{efe80ed0 #104 A=app.testapp.test U=0 StackId=1 sz=1} minWidth=-1 minHeight=-1 maxWidth=-1 maxHeight=-1
09-13 13:38:24.116  3741 11514 D ActivityManager: moveToFront() : reason=startedActivity setFocusedActivity isAttached=true TaskRecord{efe80ed0 #104 A=app.testapp.test U=0 StackId=1 sz=1}
09-13 13:38:24.117  3741 11514 D InputDispatcher: Focused application set to: xxxx
09-13 13:38:24.117  3741  3786 D WindowManager: set systemUiVisibility of statusbar : vis= 0x2608
09-13 13:38:24.117  3741 11514 D InputDispatcher: Focus left window: 26529
09-13 13:38:24.118  3741 11514 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{efe80ed0 #104 A=app.testapp.test U=0 StackId=1 sz=1} next=ActivityRecord{30871c2d0 u0 app.testapp.test/sh.calaba.instrumentationbackend.StatusReporterActivity t104} mFocusedStack=ActivityStack{697e16ad0 stackId=1, 3 tasks}
09-13 13:38:24.118  3741 11514 D ActivityTrigger: ActivityTrigger activityPauseTrigger
09-13 13:38:24.118  3741 11514 D GameManagerService: sem_perfomance_mode: 0
09-13 13:38:24.121 30348 30348 D AndroidRuntime: Shutting down VM
09-13 13:38:24.121 30348 30348 E AndroidRuntime: FATAL EXCEPTION: main
09-13 13:38:24.121 30348 30348 E AndroidRuntime: Process: app.testapp, PID: 30348
09-13 13:38:24.121 30348 30348 E AndroidRuntime: java.lang.RuntimeException: Exception thrown in onCreate() of ComponentInfo{app.testapp.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}: java.lang.RuntimeException: java.io.FileNotFoundException: actions
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5879)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: actions
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.actions.Actions.loadActions(Actions.java:44)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.actions.Actions.<init>(Actions.java:29)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.entrypoint.AndroidInstrumentationStartup.setup(AndroidInstrumentationStartup.java:122)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.entrypoint.AndroidInstrumentationStartup.start(AndroidInstrumentationStartup.java:93)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.Main.start(Main.java:10)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.CalabashInstrumentation.onCreate(CalabashInstrumentation.java:34)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	... 8 more
09-13 13:38:24.121 30348 30348 E AndroidRuntime: Caused by: java.io.FileNotFoundException: actions
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.content.res.AssetManager.openAsset(Native Method)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:421)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at android.content.res.AssetManager.open(AssetManager.java:395)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	at sh.calaba.instrumentationbackend.actions.Actions.loadActions(Actions.java:34)
09-13 13:38:24.121 30348 30348 E AndroidRuntime: 	... 14 more
09-13 13:38:24.122  3741  3815 D WindowManager: addWindow: android.view.ViewRootImpl$W@5cd3fc3 displayId=0
09-13 13:38:24.123  3741  3815 D InputTransport: Input channel constructed: fd=142
09-13 13:38:24.123  3741  3815 D InputTransport: Input channel constructed: fd=402
09-13 13:38:24.123  3741  3815 D ViewRootImpl@de4cf72[test]: setView = DecorView@ccc8b79[test] touchMode=true
09-13 13:38:24.125  3741  3946 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{7ae1fced0 #95 A=com.android.settings U=0 StackId=1 sz=2} next=ActivityRecord{30871c2d0 u0 app.testapp.test/sh.calaba.instrumentationbackend.StatusReporterActivity t104} mFocusedStack=ActivityStack{697e16ad0 stackId=1, 3 tasks}
09-13 13:38:24.137  3741  3815 V WindowManager: Relayout Window{5a3c040d0 u0 Starting app.testapp.test}: viewVisibility=0 req=1080x1848 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#81830118 pfl=0x11 wanim=0x103038a vsysui=0x600 needsMenuKey=2 naviIconColor=0}
09-13 13:38:24.138  3184  3184 I SurfaceFlinger: id=703 createSurf (1x1),1 flag=404, uest
09-13 13:38:24.152  3741  3815 D WindowManager: finishDrawingWindow: Window{5a3c040d0 u0 Starting app.testapp.test} mDrawState=DRAW_PENDING
09-13 13:38:24.152  3741  3815 D ViewRootImpl@de4cf72[test]: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
09-13 13:38:24.155  3741  3946 D GameManagerService: sem_perfomance_mode: 0
09-13 13:38:24.155  3741  3946 D MARsPolicyManager: handlePackageResumedFG pkgName = app.testapp.test, userId = 0
09-13 13:38:24.159  3741  4811 D Debug   : !@DumpState : SHIP
09-13 13:38:24.159 26529 26529 D ViewRootImpl@941412e[Settings$ManageApplicationsActivity]: MSG_WINDOW_FOCUS_CHANGED 0
09-13 13:38:24.160  3741  4811 D Debug   : !@DumpState : debug level:0x4f4c
09-13 13:38:24.160  3741  4811 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
09-13 13:38:24.160 30348 30348 I Process : Sending signal. PID: 30348 SIG: 9
09-13 13:38:24.161  3741  3741 D GameManagerService: NotifyRunnable. pkg: app.testapp.test, type: 4, isMinimized: false, isTunableApp: false
09-13 13:38:24.161  3741  3741 D GameManagerService: unexpected mPrevNotiType: -1
09-13 13:38:24.163  4707  6426 D ForegroundUtils: could not check pending caller
09-13 13:38:24.164 30274 30274 I System.out: Failure file: /data/user/0/app.testapp.test/files/calabash_failure.out
09-13 13:38:24.165 30274 30274 I System.out: Finished file: /data/user/0/app.testapp.test/files/calabash_finished.out
09-13 13:38:24.165 30274 30274 I System.out: method: report-failure
09-13 13:38:24.165 30274 30274 I System.out: Failure state: Unknown error:
09-13 13:38:24.165 30274 30274 I System.out: java.lang.RuntimeException: java.io.FileNotFoundException: actions
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.actions.Actions.loadActions(Actions.java:44)
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.actions.Actions.<init>(Actions.java:29)
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.entrypoint.AndroidInstrumentationStartup.setup(AndroidInstrumentationStartup.java:122)
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.entrypoint.AndroidInstrumentationStartup.start(AndroidInstrumentationStartup.java:93)
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.Main.start(Main.java:10)
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.CalabashInstrumentation.onCreate(CalabashInstrumentation.java:34)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.os.Looper.loop(Looper.java:154)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
09-13 13:38:24.165 30274 30274 I System.out: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 13:38:24.165 30274 30274 I System.out: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
09-13 13:38:24.165 30274 30274 I System.out: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
09-13 13:38:24.165 30274 30274 I System.out: Caused by: java.io.FileNotFoundException: actions
09-13 13:38:24.165 30274 30274 I System.out: 	at android.content.res.AssetManager.openAsset(Native Method)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.content.res.AssetManager.open(AssetManager.java:421)
09-13 13:38:24.165 30274 30274 I System.out: 	at android.content.res.AssetManager.open(AssetManager.java:395)
09-13 13:38:24.165 30274 30274 I System.out: 	at sh.calaba.instrumentationbackend.actions.Actions.loadActions(Actions.java:34)
09-13 13:38:24.165 30274 30274 I System.out: 	... 14 more
09-13 13:38:24.170  3741  5787 D GameManagerService: identifyGamePackage. app.testapp.test
09-13 13:38:24.170  3741  5787 D GameManagerService: identifyGamePackage. app.testapp.test
09-13 13:38:24.171  3741  3815 V WindowManager: Relayout Window{5a3c040d0 u0 Starting app.testapp.test}: viewVisibility=0 req=1080x1920 WM.LayoutParams{(0,0)(fillxfill) sim=#20 ty=3 fl=#81830118 pfl=0x11 wanim=0x103038a vsysui=0x600 needsMenuKey=2 naviIconColor=0}
09-13 13:38:24.173  3741  3786 D WindowManager: set systemUiVisibility of statusbar : vis= 0x608
09-13 13:38:24.174  3741  3936 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root is not base activity
09-13 13:38:24.177  3741  4776 D WindowManager: adjustSystemUiVisibilityLw : vis= 0x608
09-13 13:38:24.179  3741  3936 D ActivityManager: moveToFront() : reason=finishActivity adjustFocus setFocusedActivity isAttached=true TaskRecord{7ae1fced0 #95 A=com.android.settings U=0 StackId=1 sz=2}
09-13 13:38:24.179  3741 11509 V WindowManager: Relayout Window{96e32afd0 u0 com.android.settings/com.android.settings.Settings$ManageApplicationsActivity}: viewVisibility=8 req=1080x1920 WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#81810100 pfl=0x20000 wanim=0x103038a vsysui=0x2600 needsMenuKey=2 naviIconColor=0}
09-13 13:38:24.186  3741  3936 D InputDispatcher: Focused application set to: xxxx
09-13 13:38:24.187  3741  3936 D ActivityTrigger: ActivityTrigger activityPauseTrigger
09-13 13:38:24.187  3741  3936 D GameManagerService: sem_perfomance_mode: 0
09-13 13:38:24.187  3741  3815 D WindowManager: finishDrawingWindow: Window{5a3c040d0 u0 Starting app.testapp.test} mDrawState=HAS_DRAWN
09-13 13:38:24.189  3741  4768 I ActivityManager: Process app.testapp (pid 30348) has died(155,1668)
09-13 13:38:24.189  3741  4768 D ActivityManager: cleanUpApplicationRecord -- 30348
09-13 13:38:24.192  3741  4768 W ActivityManager: Crash of app app.testapp running instrumentation ComponentInfo{app.testapp.test/sh.calaba.instrumentationbackend.CalabashInstrumentationTestRunner}
09-13 13:38:24.192  3741  4768 I ActivityManager: Force stopping app.testapp appid=10294 user=0: finished inst
09-13 13:38:24.194  3741  4768 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=null next=ActivityRecord{686dc63d0 u0 com.android.settings/.Settings$ManageApplicationsActivity t95} mFocusedStack=ActivityStack{697e16ad0 stackId=1, 3 tasks}
09-13 13:38:24.202  4707  6426 D ForegroundUtils: could not check pending caller
09-13 13:38:24.209  3741  5787 D GameManagerService: identifyGamePackage. app.testapp.test
09-13 13:38:24.209  3741  5787 D GameManagerService: identifyGamePackage. app.testapp.test
09-13 13:38:24.215 22663 22663 I DMT-DropBoxReceiver: Received : android.intent.action.DROPBOX_ENTRY_ADDED
09-13 13:38:24.215 22663 22663 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1403 android.content.ContextWrapper.startService:664 android.content.ContextWrapper.startService:664 com.samsung.android.sm.common.DropBoxReceiver.a:47 com.samsung.android.sm.common.DropBoxReceiver.onReceive:29
09-13 13:38:24.223  3741 11511 D ActivityManager: resumeTopActivityInnerLocked() : #1 prevTask=TaskRecord{efe80ed0 #104 A=app.testapp.test U=0 StackId=1 sz=1} next=ActivityRecord{686dc63d0 u0 com.android.settings/.Settings$ManageApplicationsActivity t95} mFocusedStack=ActivityStack{697e16ad0 stackId=1, 3 tasks}
09-13 13:38:24.245  3741  4777 V WindowManager: Relayout Window{96e32afd0 u0 com.android.settings/com.android.settings.Settings$ManageApplicationsActivity EXITING}: viewVisibility=0 req=1080x1920 WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#81810100 pfl=0x20000 wanim=0x103038a vsysui=0x2600 needsMenuKey=2 naviIconColor=0}
09-13 13:38:24.245  3741  4777 D WindowManager: relayoutVisibleWindow: Window{96e32afd0 u0 com.android.settings/com.android.settings.Settings$ManageApplicationsActivity EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
09-13 13:38:24.246  3741  3786 D WindowManager: set systemUiVisibility of statusbar : vis= 0x2608
09-13 13:38:24.251  3741  4777 D InputDispatcher: Focus entered window: 26529
09-13 13:38:24.251  3741  4768 D WindowManager: adjustSystemUiVisibilityLw : vis= 0x2608
09-13 13:38:24.255 26529 27255 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
09-13 13:38:24.257  3741 11511 D GameManagerService: sem_perfomance_mode: 0
09-13 13:38:24.257  3741  3741 D GameManagerService: NotifyRunnable. pkg: com.android.settings, type: 4, isMinimized: false, isTunableApp: false
09-13 13:38:24.257  3741  3741 D GameManagerService: unexpected mPrevNotiType: -1
09-13 13:38:24.257  3741 11511 D MARsPolicyManager: handlePackageResumedFG pkgName = com.android.settings, userId = 0
09-13 13:38:24.269  3741  4769 D WindowManager: finishDrawingWindow: Window{96e32afd0 u0 com.android.settings/com.android.settings.Settings$ManageApplicationsActivity} mDrawState=HAS_DRAWN
09-13 13:38:24.280  3741  3741 I Telecom : TelecomFeature: getContactsPackageName: com.samsung.android.contacts: TSI.gDDP@Ah8
09-13 13:38:24.280  3741  3741 I Telecom : com.android.server.telecom.TelecomServiceImpl$1: getSystemDialerPackage: com.samsung.android.contacts: TSI.gDDP@Ah8
09-13 13:38:24.280  3741  3741 I Telecom : TelecomFeature: getContactsPackageName: com.samsung.android.contacts
09-13 13:38:24.289  3741  3815 D KnoxTimeoutHandler: notifyActivityDrawn [MsgParam] userId: 0 fullscreen is true showWhenlocked is false isMutiwindowRecord is false multiwindowstyle is 1
09-13 13:38:24.289  3741  3741 D KnoxTimeoutHandler: activityDrawn [MsgParam] userId: 0 fullscreen is true showWhenlocked is false isMutiwindowRecord is false multiwindowstyle is 1
09-13 13:38:24.290  3741  3741 I KnoxTimeoutHandler: SD activityfalse
09-13 13:38:24.290  3741  3741 I KnoxTimeoutHandler: Fullscreen and mCurrent is not KNOX user. Hence hide keyguard
09-13 13:38:24.293  3741  4010 D MdnieScenarioControlService:  packageName : com.android.settings    className : com.android.settings.Settings$ManageApplicationsActivity
09-13 13:38:24.295 22663 30379 V CrashedAppLogging: isMasterSwitchOff : false
09-13 13:38:24.307 22663 30379 W PkgUtils: p: app.testapp, u:0
09-13 13:38:24.380  3741  4318 D ActivityManager: post active user change for 0 fullscreen true isHomeActivity() false
09-13 13:38:24.380  3741  4318 D KnoxTimeoutHandler: postActiveUserChange [MsgParam] userId: 0 fullscreen is true showWhenlocked is false isMutiwindowRecord is false multiwindowstyle is 0
09-13 13:38:24.380  3741  3741 D KnoxTimeoutHandler: handleActiveUserChange [MsgParam] userId: 0 fullscreen is true showWhenlocked is false isMutiwindowRecord is false multiwindowstyle is 0
09-13 13:38:24.380 26529 26529 D ViewRootImpl@941412e[Settings$ManageApplicationsActivity]: MSG_WINDOW_FOCUS_CHANGED 1
09-13 13:38:24.381  3741  3741 I KnoxTimeoutHandler: Shared devices show user statefalse
09-13 13:38:24.381  3741  4326 D InputMethodManagerService: windowGainedFocus mCurrentFocusedUserId - 0 and mSecureKeypadEnabled-false
09-13 13:38:24.384  3741 11514 V WindowManager: Relayout Window{96e32afd0 u0 com.android.settings/com.android.settings.Settings$ManageApplicationsActivity}: viewVisibility=0 req=1080x1920 WM.LayoutParams{(0,0)(fillxfill) sim=#10 ty=1 fl=#81810100 pfl=0x20000 wanim=0x103038a vsysui=0x2600 needsMenuKey=2 naviIconColor=0}
09-13 13:38:24.387 26529 27282 W ApplicationsState: Cannot find pkg: com.samsung.android.game.gamehome on user 0
09-13 13:38:24.392  3741  3750 I art     : Background partial concurrent mark sweep GC freed 78723(5MB) AllocSpace objects, 6(120KB) LOS objects, 24% free, 50MB/66MB, paused 1.681ms total 147.633ms
```

**Comment by harvinderkaur** [comment]
can someone provides the exacts steps to fix it.
