### ISSUE TITLE
'start_test_server_in_background' has issue with new version 0.9.6

### ISSUE THREAD

**Issue by aosng007** [calabash/calabash-android#893]
Following command executed with different results by calabash-android version 0.9.5 and 0.9.6

_calabash-android resign <location of apk>
calabash-android console <location of apk>
reinstall_apps
reinstall_test_server
start_test_server_in_background_

- with calabash-android 0.9.5 and rubyzip 1.2.1  -> apk lunched successfully after executed start_test_server_in_background.

- with calabash-android 0.9.6 and rubyzip 1.2.2 (which needs to be updated as well if execute cmd with bundle exec),  I get error message when execute calabash-android console <apk>
_No test server found for this combination of app and calabash version. Recreating test server.
**WARNING: skipped META-INF/CERT.RSA as unsafe
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:188:in `block (2 levels) in fingerprint_from_apk': No signature files found in META-INF. Cannot proceed. (Run
timeError)**
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:170:in `chdir'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:170:in `block in fingerprint_from_apk'
from C:/Ruby22-x64/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:169:in `fingerprint_from_apk'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/bin/calabash-android-build.rb:2:in `calabash_build'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/lib/calabash-android/helpers.rb:107:in `build_test_server_if_needed'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/bin/calabash-android-console.rb:26:in `calabash_console'
from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.6/bin/calabash-android:107:in `<top (required)>'
from C:/Ruby22-x64/bin/calabash-android:23:in `load'
from C:/Ruby22-x64/bin/calabash-android:23:in `<main>'_

- After I manually downgrade rubyzip1.2.2 to 1.2.1, kept calabash-android in 0.9.6 and tried again, I Failed to start the app when executing start_test_server_in_background
_irb(main):001:0> start_test_server_in_background
RuntimeError: App did not start see adb logcat for details
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/operations.rb:743:in `block in start_test_server_in_background'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/retry.rb:10:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/retry.rb:10:in `block in retry'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/retry.rb:8:in `times'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/retry.rb:8:in `retry'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/operations.rb:742:in `start_test_server_in_background'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/calabash-android-0.9.5/lib/calabash-android/operations.rb:152:in `start_test_server_in_background'
        from (irb):1
        from C:/Ruby22-x64/bin/irb:11:in `<main>'_
And in the adb logcat, it mentioned _‘E adbd    : failed to connect to socket 'tcp:7102': Connection refused’_

**Comment by ruttuk** [comment]
I'm having the exact same issue. If someone could post a solution it would be appreciated!

**Comment by aosng007** [comment]
@ruttuk , I've worked out a temp solution that specify version with calabash-android 0.9.5 and rubyzip 1.2.1 in Gemfile, which can stop automatically upgrade into up-to-date version

**Comment by harvinderkaur** [comment]
I have updated my gemfile -
 # frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'calabash-android', '0.9.5'
gem 'rubyzip', '1.2.1'
# gem "rails"

and also added this in gemfile as well
source 'https://rubygems.org'

gem 'calabash-android', '0.9.5'
gem 'cucumber'
gem 'mongo'
gem 'json'
gem 'rubyzip', '1.2.1'

but still having issues - RuntimeError: Failed to start application. Starting took more than 60 seconds: HTTPClient::ReceiveTimeoutError - execution expired

**Comment by harvinderkaur** [comment]
Can someone share the exacts steps on how to get it working.

**Comment by gunesmes** [comment]
@harvinderkaur have you uninstalled the instrument_backend app in your device?

**Comment by AndreyMitsyk** [comment]
@harvinderkaur just remove it from app list e.g. on clear android: settings->Apps&notification -> See all apps ->instrument_backend -> uninstall

**Comment by harvinderkaur** [comment]
@AndreyMitsyk - Have tried and I still get the same error.
