### ISSUE TITLE
Unable resign the apk file- Showing the alert as  "No such file or directory - "C:/android-sdks/platform-tools/aapt"

### ISSUE THREAD

**Issue by Pradeeplogicvalley** [calabash/calabash-android#923]
I've done the all steps in calabash and trying to resign the apk it showing alert as,
C:\Ruby27-x64\lib\ruby\gems\2.7.0\gems\calabash-android-0.4.21>calabash-android resign A.apk
Traceback (most recent call last):
        7: from C:/Ruby27-x64/bin/calabash-android:23:in `<main>'
        6: from C:/Ruby27-x64/bin/calabash-android:23:in `load'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/calabash-android-0.4.21/bin/calabash-android:95:in `<top (required)>'
        4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/calabash-android-0.4.21/lib/calabash-android/helpers.rb:51:in `resign_apk'
        3: from C:/Ruby27-x64/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/calabash-android-0.4.21/lib/calabash-android/helpers.rb:56:in `block in resign_apk'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/calabash-android-0.4.21/lib/calabash-android/helpers.rb:63:in `unsign_apk'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/calabash-android-0.4.21/lib/calabash-android/helpers.rb:63:in ``': No such file or directory - "C:/android-sdks/platform-tools/aapt" list "C:/Users/pradeep.k/AppData/Local/Temp/d20200911-7720-1n0fjk3/unsigned.apk" (Errno::ENOENT)

**Comment by mreid-projects** [comment]
Did you manage to fix this?

**Comment by Pradeeplogicvalley** [comment]
Not yet
